import { escapePackageAttribute, renderPackageInline, renderPackageProse } from "../../sdk/html.js";
import { academicProfile } from "../../sdk/academic.js";

function renderSystemNode(node) {
  return `<span class="package-system-node" data-system-node-id="${escapePackageAttribute(node.id)}" data-system-node-kind="${escapePackageAttribute(node.kind)}"><span class="package-system-node-kind">${renderPackageInline(node.kind)}</span><strong>${renderPackageInline(node.label)}</strong></span>`;
}

function renderSystemGroups(data) {
  const children = new Map(data.groups.map(({ id }) => [id, []]));
  data.groups.forEach((group) => { if (group.parentId && children.has(group.parentId)) children.get(group.parentId).push(group); });
  const nodesByGroup = new Map(data.groups.map(({ id }) => [id, data.nodes.filter(({ groupId }) => groupId === id)]));
  const renderGroup = (group) => `<section class="package-system-group" data-system-group-id="${escapePackageAttribute(group.id)}" data-system-group-kind="${escapePackageAttribute(group.kind)}"><header><span>${renderPackageInline(group.kind)}</span><h4>${renderPackageInline(group.label)}</h4></header><div class="package-system-group-content">${nodesByGroup.get(group.id).map(renderSystemNode).join("")}${children.get(group.id).map(renderGroup).join("")}</div></section>`;
  return data.groups.filter(({ parentId }) => parentId === null).map(renderGroup).join("");
}

export const systemMapPackage = Object.freeze({
  manifest: Object.freeze({ id: "aralearn.resource.system_map", version: "1.0.0", label: "Mapa de sistema", purpose: "Representar limites, componentes e conexões de um sistema técnico.", slots: Object.freeze(["content", "feedback"]), cognitiveOperations: Object.freeze(["locate-component", "trace-dependency", "inspect-boundary", "explain-architecture"]), academic: academicProfile({ domains: ["arquitetura de software", "computação em nuvem", "infraestrutura"], knowledgeObjects: ["limite de sistema", "componente", "dependência"], conventions: ["limites nomeados", "componentes tipados", "conexões descritas"], appropriateWhen: ["pertencimento a limites altera a interpretação"], avoidWhen: ["uma topologia, árvore ou sequência simples basta"], technologies: ["HTML semântico", "CSS lógico"], practiceModes: ["exposition", "gap", "typing", "selection", "classification"] }), responseCompatibility: Object.freeze(["aralearn.response.gap", "aralearn.response.choice"]), limitations: Object.freeze(["Não use para uma cadeia simples nem para topologia sem limites significativos." ]), accessibility: "Grupos, componentes e conexões possuem uma lista textual completa."
  }),
  authoringContract: Object.freeze({ intent: "Declare grupos aninhados, componentes e links; não declare coordenadas.", required: Object.freeze(["groups", "nodes", "links"]), optional: Object.freeze(["prompt"]), rules: Object.freeze(["Toda referência precisa existir.", "Limites têm significado explicado."]), example: Object.freeze({ prompt: "Observe o limite da aplicação.", groups: [{ id: "app", label: "Aplicação", kind: "boundary", parentId: null }], nodes: [{ id: "client", label: "Cliente", kind: "client", groupId: null }, { id: "api", label: "API", kind: "service", groupId: "app" }], links: [{ id: "request", from: "client", to: "api", label: "requisição", directed: true }] }) }),
  schema: Object.freeze({ type: "object", additionalProperties: false, required: ["groups", "nodes", "links"], properties: { prompt: { type: "string" }, groups: { type: "array", maxItems: 20, items: { type: "object", additionalProperties: false, required: ["id", "label", "kind", "parentId"], properties: { id: { type: "string" }, label: { type: "string" }, kind: { type: "string", enum: ["region", "zone", "network", "cluster", "namespace", "container", "stage", "boundary"] }, parentId: { anyOf: [{ type: "string" }, { type: "null" }] } } } }, nodes: { type: "array", minItems: 1, maxItems: 40, items: { type: "object", additionalProperties: false, required: ["id", "label", "kind", "groupId"], properties: { id: { type: "string" }, label: { type: "string" }, kind: { type: "string", enum: ["client", "service", "database", "queue", "storage", "gateway", "worker", "external"] }, groupId: { anyOf: [{ type: "string" }, { type: "null" }] } } } }, links: { type: "array", maxItems: 80, items: { type: "object", additionalProperties: false, required: ["id", "from", "to", "label", "directed"], properties: { id: { type: "string" }, from: { type: "string" }, to: { type: "string" }, label: { type: "string" }, directed: { type: "boolean" } } } } } }),
  normalize(data) { return { ...(data?.prompt ? { prompt: String(data.prompt).trim() } : {}), groups: (data?.groups || []).map((item) => ({ ...item, id: String(item.id), label: String(item.label), kind: String(item.kind), parentId: item.parentId == null ? null : String(item.parentId) })), nodes: (data?.nodes || []).map((item) => ({ ...item, id: String(item.id), label: String(item.label), kind: String(item.kind), groupId: item.groupId == null ? null : String(item.groupId) })), links: (data?.links || []).map((item) => ({ id: String(item.id), from: String(item.from), to: String(item.to), label: String(item.label), directed: Boolean(item.directed) })) }; },
  validate(data) { const groups = new Set(data.groups.map(({ id }) => id)); const nodes = new Set(data.nodes.map(({ id }) => id)); const errors = []; if (groups.size !== data.groups.length || nodes.size !== data.nodes.length) errors.push("Grupos e nós precisam de ids únicos em seus escopos."); if (data.groups.some(({ parentId }) => parentId && !groups.has(parentId))) errors.push("Grupo referencia pai inexistente."); if (data.nodes.some(({ groupId }) => groupId && !groups.has(groupId))) errors.push("Nó referencia grupo inexistente."); if (data.links.some(({ from, to }) => !nodes.has(from) || !nodes.has(to))) errors.push("Link referencia nó inexistente."); return errors; },
  render(data) { const groupName = new Map(data.groups.map(({ id, label }) => [id, label])); const nodeName = new Map(data.nodes.map(({ id, label }) => [id, label])); const ungrouped = data.nodes.filter(({ groupId }) => groupId === null); return `<div class="runtime-block runtime-system-map-block">${data.prompt ? renderPackageProse(data.prompt) : ""}<div class="package-system-map">${ungrouped.length ? `<section class="package-system-ungrouped" aria-label="Componentes externos">${ungrouped.map(renderSystemNode).join("")}</section>` : ""}<div class="package-system-groups">${renderSystemGroups(data)}</div><ol class="package-system-links">${data.links.map((link, index) => `<li><span class="package-system-link-number">${index + 1}</span><span><strong>${renderPackageInline(nodeName.get(link.from))}</strong> <span class="package-system-link-arrow" aria-hidden="true">${link.directed ? "→" : "—"}</span> <strong>${renderPackageInline(nodeName.get(link.to))}</strong><small>${renderPackageInline(link.label)}</small></span></li>`).join("")}</ol></div><p class="visually-hidden">${data.nodes.map((node) => `${node.label}${node.groupId ? ` em ${groupName.get(node.groupId)}` : " fora dos grupos"}`).join("; ")}</p></div>`; },
  accessibleText(data) { const names = new Map(data.nodes.map(({ id, label }) => [id, label])); return `${data.groups.map((group) => `Grupo ${group.label}`).join(". ")}. ${data.nodes.map((node) => `Componente ${node.label}`).join(". ")}. ${data.links.map((link) => `${names.get(link.from)} ${link.label} ${names.get(link.to)}`).join(". ")}.`; }, editableTargets(data) { return [...(data.prompt ? [{ path: "prompt", label: "Editar orientação" }] : []), ...data.groups.map((_, index) => ({ path: `groups[${index}].label`, label: `Editar grupo ${index + 1}` })), ...data.nodes.map((_, index) => ({ path: `nodes[${index}].label`, label: `Editar componente ${index + 1}` })), ...data.links.map((_, index) => ({ path: `links[${index}].label`, label: `Editar conexão ${index + 1}` }))]; }
});
