-- Corte relacional enxuto: o ambiente local nasce sem catálogo operacional.
-- Testes que precisam de Cursos carregam suas próprias fixtures isoladas.
-- O seed nunca cria Cursos, seleções ou dados de usuário.
