import { escapePackageAttribute, renderPackageInline, renderPackageProse } from "../../sdk/html.js";
import { academicProfile } from "../../sdk/academic.js";

export const linguisticExamplePackage = Object.freeze({
  manifest: Object.freeze({
    id: "aralearn.resource.linguistic_example", version: "1.0.0", label: "Exemplo linguístico",
    purpose: "Alinhar forma, glosa e tradução em análise linguística.", slots: Object.freeze(["content", "feedback"]),
    cognitiveOperations: Object.freeze(["align-form-gloss", "compare-language-forms", "analyze-morphemes"]),
    academic: academicProfile({ domains: ["linguística", "línguas"], knowledgeObjects: ["forma linguística", "glosa", "tradução"], conventions: ["alinhamento interlinear", "glosas consistentes", "idioma e direção declarados"], appropriateWhen: ["forma, análise e tradução precisam ser alinhadas"], avoidWhen: ["uma citação simples é suficiente"], technologies: ["HTML semântico", "atributos de idioma e direção"], practiceModes: ["exposition", "gap", "typing", "selection", "matching"] }),
    responseCompatibility: Object.freeze(["aralearn.response.gap", "aralearn.response.choice"]), limitations: Object.freeze(["Não use fora de uma tarefa linguística que exija alinhamento."]),
    accessibility: "Cada unidade é lida com forma, glosa e tradução na mesma ordem."
  }),
  authoringContract: Object.freeze({ intent: "Declare unidades alinhadas e uma tradução compreensível.", required: Object.freeze(["languageTag", "writingMode", "alignment", "units"]), optional: Object.freeze(["prompt", "textDirection"]), rules: Object.freeze(["Explique convenções de glosa antes de usá-las."]), example: Object.freeze({ languageTag: "pt-BR", writingMode: "horizontal", alignment: "word", units: [{ id: "u1", form: "casas", gloss: "casa-PL", translation: "mais de uma casa" }] }) }),
  schema: Object.freeze({ type: "object", additionalProperties: false, required: ["languageTag", "writingMode", "alignment", "units"], properties: { prompt: { type: "string" }, languageTag: { type: "string", minLength: 2 }, writingMode: { type: "string", enum: ["horizontal", "vertical"] }, textDirection: { type: "string", enum: ["auto", "ltr", "rtl"] }, alignment: { type: "string", enum: ["word", "morpheme", "character"] }, units: { type: "array", minItems: 1, maxItems: 30, items: { type: "object", additionalProperties: false, required: ["id", "form", "gloss", "translation"], properties: { id: { type: "string", minLength: 1 }, form: { type: "string", minLength: 1 }, gloss: { type: "string", minLength: 1 }, translation: { type: "string", minLength: 1 } } } } } }),
  normalize(data) { return { ...(data?.prompt ? { prompt: String(data.prompt).trim() } : {}), languageTag: String(data?.languageTag || "").trim(), writingMode: String(data?.writingMode || "horizontal").trim(), ...(data?.textDirection ? { textDirection: String(data.textDirection).trim() } : {}), alignment: String(data?.alignment || "word").trim(), units: (data?.units || []).map((item) => ({ id: String(item?.id || "").trim(), form: String(item?.form || "").trim(), gloss: String(item?.gloss || "").trim(), translation: String(item?.translation || "").trim() })) }; },
  validate(data) { return new Set(data.units.map(({ id }) => id)).size === data.units.length ? [] : ["Unidades precisam de ids únicos."]; },
  render(data) { return `<div class="runtime-block runtime-linguistic-example-block" lang="${escapePackageAttribute(data.languageTag)}" dir="${escapePackageAttribute(data.textDirection || "auto")}" data-writing-mode="${escapePackageAttribute(data.writingMode)}">${data.prompt ? renderPackageProse(data.prompt) : ""}<div class="runtime-linguistic-units">${data.units.map((unit) => `<div data-unit-id="${escapePackageAttribute(unit.id)}"><span class="linguistic-form">${renderPackageInline(unit.form)}</span><span class="linguistic-gloss">${renderPackageInline(unit.gloss)}</span><span class="linguistic-translation">${renderPackageInline(unit.translation)}</span></div>`).join("")}</div></div>`; },
  accessibleText(data) { return data.units.map((unit) => `${unit.form}; glosa ${unit.gloss}; tradução ${unit.translation}.`).join(" "); },
  editableTargets(data) { return data.units.flatMap((_, index) => ["form", "gloss", "translation"].map((field) => ({ path: `units[${index}].${field}`, label: `Editar ${field} da unidade ${index + 1}` }))); },
  practiceTargets(data) { return data.units.flatMap((_, index) => ["form", "gloss", "translation"].map((field) => ({ path: `units[${index}].${field}`, label: `Lacuna em ${field} da unidade ${index + 1}`, modes: ["gap", "typing"] }))); }
});
