const E="existing",P="proposal",S="synthetic";
const badgeLabels={existing:"Capacidade existente",proposal:"Layout proposto",synthetic:"Exemplo sintético"};
const journeys={
  entrada:{label:"Entrada",ids:["login","signup","recover","newpass"]},
  estudo:{label:"Estudo",ids:["study-home","study-hierarchy","study-unit","study-practice","study-sources","study-review","study-observation","study-edit","study-provider","study-copy"]},
  autoria:{label:"Autoria",ids:["author-home","author-create","author-course","author-plan","author-part","author-parameters","parameter-1","parameter-2","parameter-3","parameter-4","author-guidance","author-components","author-sources","author-source-detail","author-structure","author-materialization","author-inspection","author-observations","author-audit","author-variants","author-research","author-people"]},
  mcp:{label:"ChatGPT / MCP",ids:["mcp-composer","mcp-connect","mcp-tools","mcp-plan","mcp-materialize","mcp-step","mcp-return"]},
  conta:{label:"Conta",ids:["settings"]}
};

function header(title,back="←",right=""){
  return `<header><button class="icon" type="button">${back}</button><h3>${title}</h3>${right?`<button class="icon" type="button">${right}</button>`:`<span style="width:40px"></span>`}</header>`;
}
function card(title,body="",extra=""){
  return `<div class="card"><h4>${title}</h4>${body}${extra}</div>`;
}
function field(label,control){return `<div class="field"><label>${label}</label>${control}</div>`;}
function button(label,primary=false){return `<button class="button ${primary?"primary ":""}block" type="button">${label}</button>`;}
function chips(items){return `<div class="chips">${items.map(x=>`<span class="chip ${x[1]?"on":""}">${x[0]}</span>`).join("")}</div>`;}
function screen(o){return o;}

const screens={
  login:screen({journey:"entrada",title:"1. Entrar",path:"AraLearn › Acesso",badges:[E],phone:`<div class="brand">AraLearn</div>${field("E-mail",'<input placeholder="E-mail">')}${field("Senha",'<input type="password" placeholder="Senha">')}<div class="footer-actions"><button class="icon" title="Criar conta">＋</button><button class="icon primary" title="Entrar">→</button><button class="icon" title="Recuperar senha">⌕</button></div>`,what:"É a porta de entrada atual do AraLearn. A autenticação usa e-mail e senha.",does:"A pessoa informa e-mail e senha e toca em Entrar. Os outros dois ícones abrem cadastro ou recuperação.",after:"Com credenciais válidas, o AraLearn abre a experiência autenticada de Estudo. Falhas permanecem nesta tela com mensagem de estado.",why:"Mantemos exatamente os três comandos que existem hoje. Não há Google, GitHub, passkey nem acesso offline nesta tela.",evidence:["src/ui/AuthGate.js"],related:["signup","recover","study-home"]}),
  signup:screen({journey:"entrada",title:"2. Criar conta",path:"Acesso › Criar conta",badges:[E],phone:`<div class="brand">AraLearn</div>${field("E-mail",'<input placeholder="E-mail">')}${field("Senha",'<input type="password" placeholder="Senha">')}<div class="footer-actions"><button class="icon">←</button><button class="icon primary">＋</button><button class="icon">✉</button></div>${card("Depois de criar",'<p class="muted">Se não houver sessão imediata: “Conta criada. Confirme pelo link enviado ao seu e-mail.”</p>')}`,what:"É o estado de cadastro do mesmo AuthGate.",does:"A pessoa informa e-mail e uma senha de pelo menos 8 caracteres. Pode voltar, criar a conta ou reenviar a confirmação.",after:"Se o Supabase devolver sessão, entra no aplicativo. Caso contrário, aguarda a confirmação enviada por e-mail.",why:"Não criamos uma página de cadastro maior: o produto atual precisa apenas desses campos e estados.",evidence:["src/ui/AuthGate.js"]}),
  recover:screen({journey:"entrada",title:"3. Pedir recuperação",path:"Acesso › Recuperar senha",badges:[E],phone:`<div class="brand">AraLearn</div>${field("E-mail",'<input placeholder="E-mail">')}<div class="footer-actions"><button class="icon">←</button><button class="icon primary">✉</button></div>${card("Resposta",'<p class="muted">“Se o endereço estiver cadastrado, o link chegará em instantes.”</p>')}`,what:"É o pedido de recuperação de senha.",does:"A pessoa informa apenas o e-mail e envia o pedido.",after:"O próximo estado acontece ao abrir o link recebido por e-mail; o AraLearn então apresenta a definição de nova senha.",why:"A resposta é deliberadamente genérica para não revelar se o e-mail está cadastrado.",evidence:["src/ui/AuthGate.js"]}),
  newpass:screen({journey:"entrada",title:"4. Definir nova senha",path:"Link de recuperação › Nova senha",badges:[E],phone:`<div class="brand">AraLearn</div>${field("Nova senha",'<input type="password" placeholder="Nova senha">')}${field("Repetir senha",'<input type="password" placeholder="Repetir senha">')}<div class="footer-actions"><button class="icon primary">✓</button></div>`,what:"É o estado aberto pelo link de recuperação.",does:"A pessoa informa a nova senha duas vezes e salva.",after:"Se as duas senhas coincidirem e a atualização for aceita, o fluxo autenticado é concluído.",why:"É uma operação curta e isolada; não precisa carregar navegação do restante do produto.",evidence:["src/ui/AuthGate.js"]}),

  "study-home":screen({journey:"estudo",title:"1. Escolher um Curso",path:"Estudo › Início",badges:[E,P,S],phone:`${header("AraLearn","","⋯")}${field("Curso",'<select><option>Fundamentos de redes · Compartilhado com você</option></select>')}${card("Fundamentos de redes",'<p class="muted">Compreender como dados percorrem redes locais e a Internet.</p><div class="meter"><span style="width:35%"></span></div><div class="row between"><span class="muted">7/20 · 3 módulos · 8 lições</span><span class="muted">35%</span></div><p class="muted">☁ Disponível com conexão</p>',button("Continuar",true))}<details class="card"><summary><strong>Rever</strong> · 2</summary><p class="muted">Unidades marcadas pela própria pessoa.</p></details><div class="footer-actions"><button class="icon primary">▤</button><button class="icon">✎</button></div>`,what:"É a entrada do percurso de Estudo. O produto atual reúne os Cursos acessíveis em um seletor e mostra uma única prévia do Curso escolhido.",does:"A pessoa troca de Curso, confere objetivo, relação de acesso, progresso e disponibilidade local e então usa Começar, Continuar ou Retomar.",after:"A composição completa do Curso é carregada quando a pessoa entra. Depois de uma abertura validada, o Curso pode ficar disponível neste dispositivo para uso sem conexão.",why:"Uma prévia por vez reduz ruído e evita capas decorativas. A alternância Estudo/Autoria fica curta e explícita.",evidence:["src/ui/renderHomeScreen.js","docs/guia-estudante.md"],related:["study-review","author-home","settings"]}),
  "study-hierarchy":screen({journey:"estudo",title:"2. Navegar pelo Curso",path:"Estudo › Curso › Módulos › Lições › Microssequências",badges:[E,P,S],phone:`${header("Fundamentos de redes")}${card("Módulo 1 · Redes e comunicação",'<div class="meter"><span style="width:60%"></span></div>'+button("Lição 1 · O que é uma rede")+button("Lição 2 · Camadas e protocolos"))}${card("Módulo 2 · Endereçamento",'<div class="meter"><span style="width:10%"></span></div>')}${button("Abrir próxima Unidade",true)}`,what:"É a hierarquia didática real: Curso → Módulo → Lição → Microssequência → Unidade de estudo.",does:"A pessoa pode seguir a continuidade automática ou abrir explicitamente um nível para mudar de contexto. Os níveis mostram progresso.",after:"Ao entrar numa Microssequência, abre uma Unidade. A posição visitada é preservada para Retomar depois.",why:"Propomos navegação progressiva e contexto visível, sem transformar cada nível em uma área global do aplicativo.",evidence:["docs/guia-estudante.md","src/study/CourseStudyApplication.js"]}),
  "study-unit":screen({journey:"estudo",title:"3. Estudar uma Unidade",path:"Estudo › … › Microssequência 2 › Unidade 1",badges:[E,P,S],phone:`${header("1 de 4")}<div class="breadcrumb">Módulo 1 › Lição 1 › Microssequência 2</div>${card("Por que protocolos existem?",'<p>Um protocolo define regras compartilhadas para que sistemas distintos interpretem a mesma troca de dados.</p><div class="mini"><strong>Exemplo</strong><p class="muted">Dois dispositivos precisam concordar sobre formato, ordem e significado das mensagens.</p></div>')}<div class="footer-actions"><button class="icon" title="Fontes">⌑</button><button class="icon" title="Rever">★</button><button class="icon" title="Observação">◌</button><button class="icon" title="Editar">✎</button></div>${button("Continuar",true)}`,what:"É a superfície principal de Estudo. A Unidade renderiza um ou mais componentes didáticos e informa o contexto curricular e a posição.",does:"A pessoa lê ou interage com o conteúdo. As ações contextuais reais incluem Fontes, Marcar para rever, Observação e Editar quando autorizado.",after:"Continuar conclui/avança conforme o componente. As ações laterais abrem folhas ou modos contextuais e depois retornam à mesma Unidade.",why:"As ações ficam perto do objeto que modificam. Não há motivo para transformar Fontes, Observações ou edição em destinos permanentes.",evidence:["docs/guia-estudante.md"],related:["study-practice","study-sources","study-review","study-observation","study-edit"]}),
  "study-practice":screen({journey:"estudo",title:"4. Responder a uma prática",path:"Estudo › Unidade › Componente de prática",badges:[E,S],phone:`${header("Prática")}${card("Qual situação exige um protocolo compartilhado?",'<label class="row"><input type="radio" name="p"> Dois sistemas trocando mensagens</label><label class="row"><input type="radio" name="p"> Um arquivo sem destinatário</label>')}${button("Continuar",true)}${card("Depois da resposta",'<p class="muted">O componente pode pedir correção, permitir nova tentativa ou mostrar retorno.</p>')}`,what:"É uma Unidade ou trecho de Unidade com componente de resposta. O catálogo inclui escolha, lacuna, ordenação e outras formas estruturadas.",does:"A pessoa responde no próprio componente e usa Continuar.",after:"Se faltar algo, o componente pede conclusão. Depois apresenta o retorno previsto e permite continuar. O AraLearn não converte isso em nota global ou ranking.",why:"A interação pertence ao próprio componente; não criamos uma tela de prova separada.",evidence:["docs/guia-estudante.md","src/components/registry.js"]}),
  "study-sources":screen({journey:"estudo",title:"5. Consultar Fontes",path:"Estudo › Unidade › Fontes",badges:[E,S],phone:`${header("Fontes")}${card("RFC 1122",'<p class="muted">Requirements for Internet Hosts — Communication Layers</p><p class="muted">Seção 1.2</p>'+button("Abrir endereço externo"))}`,what:"É uma folha contextual aberta a partir da Unidade.",does:"A pessoa consulta apenas as Fontes que a autoria decidiu tornar visíveis. Pode ver citação, localização e, quando permitido, link externo.",after:"Ao fechar, volta para a mesma Unidade.",why:"O catálogo privado, revisões, trechos de verificação e manutenção de Fontes não aparecem para o estudante.",evidence:["docs/guia-estudante.md"]}),
  "study-review":screen({journey:"estudo",title:"6. Marcar e rever",path:"Estudo › Unidade / Início › Rever",badges:[E,P,S],phone:`${header("Rever")}<div class="good">A estrela na Unidade adiciona ou remove a marca pessoal.</div>${card("Por que protocolos existem?",'<p class="muted">Módulo 1 › Lição 1 › Microssequência 2</p>'+button("Abrir Unidade",true))}${card("Endereçamento IP",'<p class="muted">Módulo 2 › Lição 1</p>'+button("Abrir Unidade"))}`,what:"Rever é uma marca pessoal, não um estado do conteúdo do Curso.",does:"Na Unidade, a pessoa ativa/desativa a marca. Na Home, abre a seção Rever e escolhe um item.",after:"O AraLearn carrega o Curso se necessário e navega diretamente até a Unidade marcada.",why:"A fila fica recolhida na Home e limitada ao Curso selecionado, evitando uma área global de tarefas.",evidence:["docs/guia-estudante.md","src/ui/renderHomeScreen.js"]}),
  "study-observation":screen({journey:"estudo",title:"7. Registrar uma Observação",path:"Estudo › Unidade › Observação",badges:[E,P],phone:`${header("Observação")}${field("Categoria",'<select><option>Dúvida</option><option>Possível erro</option><option>Trecho confuso</option><option>Sugestão</option><option>Sem categoria</option></select>')}${field("Texto",'<textarea rows="5" placeholder="Escreva a observação"></textarea>')}${button("Salvar",true)}${card("Minhas observações",'<p class="muted">Abra uma observação própria para editar, retirar ou ver eventual resposta do proprietário.</p>')}`,what:"É um registro ancorado à Unidade, com categoria, estado, sincronização e eventual resposta da pessoa proprietária.",does:"A pessoa escolhe uma categoria, escreve até 2.000 caracteres e salva. Pode ter várias Observações na mesma Unidade.",after:"O registro pode chegar à caixa de entrada do proprietário. Colegas não veem a observação; cada estudante vê as próprias.",why:"A Observação fica contextual à Unidade e volta para ela ao fechar. Corrigir o conteúdo é outro fluxo: auditoria/correção.",evidence:["docs/guia-estudante.md"]}),
  "study-edit":screen({journey:"estudo",title:"8. Editar manualmente",path:"Estudo › Unidade › Editar",badges:[E,P,S],phone:`${header("Editar","×")}<div class="warning">Somente campos textuais que o componente declara editáveis.</div>${field("Título",'<input value="Por que protocolos existem?">')}${field("Texto",'<textarea rows="8">Um protocolo define regras compartilhadas...</textarea>')}<div class="row"><button class="button">↶</button><button class="button">↷</button><button class="button">Assistência por API</button></div>${button("Salvar",true)}`,what:"É a edição contextual já existente no renderer da Unidade. Não é um editor livre nem um editor rico geral.",does:"A pessoa edita apenas os campos textuais autorizados pelo contrato do componente, pode desfazer/refazer e conferir o resultado no mesmo renderer.",after:"Se o Curso for próprio, Salvar atualiza o próprio Curso. Se for compartilhado, a primeira mudança material segue para a criação de cópia pessoal.",why:"Não adicionamos uma barra de formatação que o produto não possui. Primeiro preservamos o modelo real de edição por campos do componente.",evidence:["docs/guia-estudante.md","docs/guia-professor-autor.md"]}),
  "study-provider":screen({journey:"estudo",title:"9. Pedir ajuda a um modelo",path:"Estudo › Unidade › Editar › Assistência por API",badges:[E,P,S],phone:`${header("Assistência")}<div class="good"><strong>Serviço local</strong><br><span class="muted">Credencial fica fora do AraLearn.</span></div>${field("Modelo",'<input placeholder="modelo configurado">')}${field("Pedido",'<textarea rows="4">Torne esta explicação mais concreta sem aumentar muito o texto.</textarea>')}<div class="warning">Sai do AraLearn: pedido, campos textuais editáveis, título, papel, tópicos e mensagens anteriores. Não saem PDFs, Fontes, outras Unidades ou identidades internas.</div>${button("Pedir sugestão",true)}${card("Sugestão",'<p class="muted">Ver no conteúdo → Aplicar ao rascunho ou Descartar.</p>')}`,what:"É a assistência complementar por provider para o trecho textual que já está em edição.",does:"Em produção, a pessoa informa o modelo e o pedido; o serviço local/relay encaminha ao provider configurado. O runtime suporta OpenAI, Gemini, DeepSeek e local, mas não fixa um “DeepSeek V4”.",after:"A sugestão pode ser vista no mesmo renderer e aplicada ao rascunho. Aplicar ainda não grava: a pessoa volta ao editor e precisa Salvar.",why:"Assistência permanece subordinada à edição manual. Isso evita um segundo modelo de persistência e deixa explícita a revisão humana antes da gravação.",evidence:["src/ui/StudyUnitProviderAssistance.js","src/generation/providers/studyUnitAssistanceProviders.js","docs/assistencia-por-ia.md"]}),
  "study-copy":screen({journey:"estudo",title:"10. Salvar em uma cópia pessoal",path:"Estudo › Curso compartilhado › Editar › Salvar",badges:[E,P],phone:`${header("Salvar alteração")} ${card("Este Curso foi compartilhado com você",'<p>A alteração não muda o original. Ao salvar, o AraLearn cria um Curso pessoal privado e mantém você nesta mesma Unidade.</p>')}${button("Salvar na minha cópia",true)}${button("Cancelar")}`,what:"É o caso especial da primeira gravação material feita por quem recebeu acesso direto a um Curso de outra pessoa.",does:"A pessoa confirma que quer salvar numa cópia privada própria.",after:"O AraLearn cria a cópia na mesma transação e permanece na mesma Unidade. A cópia aparece como “Sua cópia” no Estudo e em Autoria.",why:"Abrir editor, pedir sugestão, cancelar, falhar ou salvar sem mudança não cria cópia. Só a primeira mudança material dispara o fluxo.",evidence:["docs/guia-estudante.md","CHANGELOG.md","supabase/migrations/20260821145358_personal_course_copy_edit.sql"]}),

  "author-home":screen({journey:"autoria",title:"1. Abrir a Autoria",path:"Autoria › Meus cursos",badges:[E,P,S],phone:`${header("Meus cursos","▤","＋")}${field("Buscar",'<input placeholder="Título, objetivo ou orientação">')}${card("Fundamentos de redes",'<p class="muted">Compreender como dados percorrem redes locais e a Internet.</p>'+button("Abrir",true))}${card("Sua cópia · Segurança básica",'<p class="muted">Curso pessoal criado a partir de um compartilhamento.</p>'+button("Abrir"))}`,what:"É a lista autoral. Mostra apenas Cursos que pertencem à conta autenticada.",does:"A pessoa pesquisa, abre um Curso próprio ou cria um novo.",after:"Abrir leva ao contexto do Curso. Criar pede título e objetivo e gera um Curso privado com plano vazio.",why:"Um Curso apenas compartilhado pertence ao Estudo, não à Autoria. A cópia pessoal aparece aqui porque se torna um Curso próprio.",evidence:["docs/guia-professor-autor.md"]}),
  "author-create":screen({journey:"autoria",title:"2. Criar um Curso",path:"Autoria › Meus cursos › Criar",badges:[E,P],phone:`${header("Novo Curso")}${field("Título",'<input placeholder="Título do Curso">')}${field("Objetivo instrucional",'<textarea rows="5" placeholder="O que a pessoa deverá compreender ou conseguir fazer?"></textarea>')}${button("Criar Curso",true)}`,what:"É a criação mínima do Curso atual.",does:"A pessoa informa título e objetivo e salva.",after:"O Curso nasce privado, com plano vazio e faixa inicial sugerida de 7 a 12 Partes. Quando tiver Unidades válidas, o proprietário pode abri-lo em Estudo.",why:"Não pedimos público, escopo, Fontes ou parâmetros antes de existir um Curso. Esses detalhes podem ser desenvolvidos no contexto do plano.",evidence:["docs/guia-professor-autor.md","docs/criar-cursos-pelo-chat.md"]}),
  "author-course":screen({journey:"autoria",title:"3. Trabalhar no Curso",path:"Autoria › Curso",badges:[E,P,S],phone:`${header("Fundamentos de redes","←","⋯")}${card("Próxima ação",'<p class="muted">Parte 3 · Camadas de rede · Planejada</p><div class="row"><button class="button primary">Abrir Parte</button><button class="button">ChatGPT</button></div>')}${card("Trabalho cotidiano",button("Planejamento e Partes")+button("Conteúdo / Inspeção"))}<details class="card"><summary><strong>Mais</strong></summary><div class="stack" style="margin-top:10px">${button("Parâmetros e orientação")}${button("Fontes")}${button("Revisar")}${button("Variantes")}${button("Pesquisa")}${button("Pessoas")}</div></details>`,what:"É uma proposta de página de contexto para o mesmo Curso vivo usado em Estudo e MCP. As capacidades do bloco existem; a composição desta tela é proposta.",does:"A pessoa vê primeiro o trabalho que provavelmente precisa continuar e entra em Planejamento/Partes ou Inspeção. Capacidades menos frequentes ficam disponíveis sem disputar o topo.",after:"Cada ação abre um contexto específico e retorna ao mesmo Curso.",why:"O guia atual já diz que Planejamento, Parâmetros, Fontes, Estrutura, Inspeção, Discussões/correções, Variantes, Pesquisa e Pessoas não precisam ser destinos permanentes. Esta tela aplica esse princípio.",evidence:["docs/guia-professor-autor.md"],related:["author-plan","author-inspection","author-parameters","author-sources","author-audit","author-variants","author-research","author-people"]}),
  "author-plan":screen({journey:"autoria",title:"4. Planejar e organizar Partes",path:"Autoria › Curso › Planejamento",badges:[E,P,S],phone:`${header("Planejamento")} ${card("Objetivo",'<p class="muted">Compreender como dados percorrem redes locais e a Internet.</p>')}<details class="card"><summary>Resultados de aprendizagem · 4</summary></details><details class="card"><summary>Unidades de análise · 12</summary></details><details class="card"><summary>Requisitos de evidência · 6</summary></details>${card("Parte 3 · Camadas de rede",'<div class="row between"><span class="muted">Planejada</span><span>3/4 alvos</span></div><p class="muted">Organizar a produção das Microssequências relacionadas às camadas.</p><div class="row"><button class="button">Abrir</button><button class="button">ChatGPT</button><button class="button primary">Produzir</button></div>')}`,what:"Planejamento reúne os elementos pedagógicos do Curso e as Partes de autoria.",does:"A pessoa edita título/objetivo/público/escopo/faixa de Partes e acrescenta, edita, reordena ou remove resultados, unidades de análise e requisitos de evidência. Também organiza Partes.",after:"Uma Parte pode ser aberta para conferir alvos, desenho e produção; ou pode ser trabalhada pelo ChatGPT/MCP.",why:"Listas densas ficam recolhidas; a próxima ação e o estado das Partes ficam visíveis primeiro.",evidence:["docs/guia-professor-autor.md"]}),
  "author-part":screen({journey:"autoria",title:"5. Trabalhar numa Parte",path:"Autoria › Curso › Planejamento › Parte 3",badges:[E,P,S],phone:`${header("Parte 3")} ${card("Camadas de rede",'<p class="muted">Intenção: produzir as Microssequências que explicam o papel e a relação entre camadas.</p><div class="chips"><span class="chip on">Planejada</span><span class="chip">3 Microssequências</span></div>')}${card("Alvos",'<p>✓ Micro 1 · visão geral</p><p>○ Micro 2 · encapsulamento</p><p>○ Micro 3 · comparação</p>')}<div class="row"><button class="button">Desenho</button><button class="button">Fontes</button></div>${button("Produzir / Retomar",true)}${button("Preparar pedido para ChatGPT")}`,what:"Parte é a unidade operacional usada para organizar a produção, não um nível didático.",does:"A pessoa confere intenção, ordem e Microssequências vinculadas; pode mover alvos, dividir/unir Parte, consultar desenho/Fontes e iniciar ou retomar produção.",after:"Produzir inicia/retoma materialização. ChatGPT prepara o fluxo conversacional sobre esta Parte.",why:"As ações que o autor tende a usar em sequência ficam juntas: contexto → desenho/Fontes → produção → conferência.",evidence:["docs/guia-professor-autor.md","docs/criar-cursos-pelo-chat.md"]}),
  "author-parameters":screen({journey:"autoria",title:"6. Ver o desenho efetivo",path:"Autoria › Curso / Lição / Microssequência › Parâmetros",badges:[E,P],phone:`${header("Parâmetros")}<div class="breadcrumb">Curso › Lição 2 › Microssequência 1</div>${card("Valores efetivos",'<div class="param"><div><strong>Novas unidades de análise</strong><div class="note">herdado do Curso</div></div><div class="value">2</div></div><div class="param"><div><strong>Formas de explicação</strong><div class="note">definição, exemplo, mecanismo, contraste</div></div><div class="value">4</div></div><div class="param"><div><strong>Oportunidades de prática</strong><div class="note">definido na Lição</div></div><div class="value">2</div></div><div class="param"><div><strong>Variação da prática</strong><div class="note">caso ou dados</div></div><div class="value">1</div></div>')}${button("Orientação autoral")}${button("Política de componentes")}`,what:"É a leitura do desenho pedagógico efetivo num escopo. O AraLearn possui exatamente quatro parâmetros canônicos.",does:"A pessoa percorre Curso, Módulo, Lição e Microssequência para ver valor efetivo, origem e escopo de herança. Pode definir localmente nos escopos permitidos ou remover a definição para restaurar herança.",after:"Uma mudança de parâmetro afeta o contexto usado em materializações futuras naquele escopo. O Módulo apenas mostra valores herdados dos quatro parâmetros.",why:"Mostramos primeiro valor e origem. Construto, justificativa, limitações e edição ficam acessíveis no detalhe de cada parâmetro.",evidence:["src/domain/courseDesignParameters.js","docs/guia-professor-autor.md"],related:["parameter-1","parameter-2","parameter-3","parameter-4","author-guidance","author-components"]}),
  "parameter-1":screen({journey:"autoria",title:"7. Parâmetro 1 — granularidade",path:"Parâmetros › Novas unidades de análise por Unidade expositiva",badges:[E,P,S],phone:`${header("Novas unidades")}${card("Valor efetivo",'<div class="row between"><strong>2</strong><span class="muted">herdado do Curso</span></div>')}${field("Definir neste escopo",'<input type="number" min="1" max="64" value="2">')}${card("Em linguagem simples",'<p>Quantos itens da análise instrucional podem ser introduzidos como novos numa mesma Unidade expositiva.</p>')}${card("Exemplo",'<p class="muted">Valor 1 → uma Unidade expositiva deveria introduzir apenas uma nova unidade de análise por vez.</p>')}`,what:"Controla a granularidade declarada da introdução de novas unidades de análise instrucional.",does:"A pessoa escolhe um inteiro de 1 a 64 ou remove a definição local para herdar o valor superior. O padrão do produto é 2.",after:"A materialização registra quais unidades de análise foram introduzidas e pode confrontar esse fato com o teto efetivo.",why:"O detalhe explica o significado e o limite antes de pedir um número. Isso reduz o risco de o autor tratar o parâmetro como uma medida de qualidade.",evidence:["src/domain/courseDesignParameters.js"],note:"A contagem não mede carga cognitiva, dificuldade, aprendizagem ou qualidade da explicação."}),
  "parameter-2":screen({journey:"autoria",title:"8. Parâmetro 2 — formas de explicação",path:"Parâmetros › Formas de explicação requeridas",badges:[E,P,S],phone:`${header("Formas de explicação")}${chips([["Definição direta",true],["Exemplo concreto",true],["Mecanismo",true],["Contraste",true],["Condição de aplicação",false],["Limite / exceção",false],["Exemplo resolvido",false],["Relação entre representações",false]])}${card("Exemplo",'<p class="muted">Se ficam marcadas definição + exemplo + contraste, a produção deve declarar essas formas quando aplicáveis à unidade de análise.</p>')}`,what:"Define quais formas semanticamente distintas de explicação precisam aparecer quando aplicáveis.",does:"A pessoa escolhe de 1 a 8 formas. O padrão é definição direta, exemplo concreto, mecanismo e contraste.",after:"A produção declara as formas efetivamente desenvolvidas ou registra por que alguma não se aplica. O AraLearn pode confrontar planejado e aplicado.",why:"Usamos rótulos humanos em vez dos identificadores técnicos do contrato.",evidence:["src/domain/courseDesignParameters.js"],note:"As formas não são uma escala universal de qualidade; adequação depende do objeto, público, tarefa e representação."}),
  "parameter-3":screen({journey:"autoria",title:"9. Parâmetro 3 — oportunidades de prática",path:"Parâmetros › Oportunidades distintas por requisito de evidência",badges:[E,P,S],phone:`${header("Oportunidades")}${card("Valor efetivo",'<div class="row between"><strong>2</strong><span class="muted">definido na Lição</span></div>')}${field("Definir neste escopo",'<input type="number" min="1" max="64" value="2">')}${card("Exemplo",'<p class="muted">Requisito: identificar a camada responsável. Valor 2 → ao menos duas oportunidades semanticamente distintas relacionadas a esse requisito.</p>')}`,what:"Define a quantidade mínima de oportunidades de prática distintas relacionadas a cada requisito de evidência.",does:"A pessoa escolhe um inteiro de 1 a 64; o padrão é 2.",after:"A produção registra identidades distintas de oportunidade por requisito e o AraLearn confronta a contagem com o mínimo efetivo.",why:"O exemplo mostra o que “oportunidade distinta” pretende significar, sem afirmar que quantidade prova domínio.",evidence:["src/domain/courseDesignParameters.js"],note:"Quantidade de oportunidades não demonstra domínio, eficácia ou equivalência entre tarefas."}),
  "parameter-4":screen({journey:"autoria",title:"10. Parâmetro 4 — variação da prática",path:"Parâmetros › Dimensões requeridas de variação",badges:[E,P,S],phone:`${header("Variação da prática")}${chips([["Caso ou dados",true],["Contexto",false],["Característica da tarefa",false],["Representação externa",false],["Nível de suporte",false]])}${card("Exemplo",'<p class="muted">Com “caso ou dados”, duas oportunidades para o mesmo requisito devem variar semanticamente o caso/dado, e não apenas trocar ordem ou aparência.</p>')}`,what:"Define quais dimensões precisam variar entre oportunidades do mesmo requisito de evidência.",does:"A pessoa escolhe de 1 a 5 dimensões. O padrão é caso ou dados.",after:"A produção declara as dimensões de variação de cada oportunidade; mudanças apenas cosméticas não contam como variação semântica.",why:"A seleção é pequena e concreta; o detalhe explica a semântica antes da escolha.",evidence:["src/domain/courseDesignParameters.js"],note:"Variação declarada não prova transferência nem aprendizagem."}),
  "author-guidance":screen({journey:"autoria",title:"11. Dar orientação autoral",path:"Autoria › Escopo › Orientação autoral",badges:[E,P,S],phone:`${header("Orientação autoral")}${field("Orientação",'<textarea rows="8">Use exemplos próximos de redes domésticas e evite pressupor conhecimento de roteamento.</textarea>')}${button("Salvar orientação",true)}<details class="card"><summary>Interpretação estruturada</summary><p class="muted">Resumo · requerer · evitar · preferir · divergências · perguntas</p></details>`,what:"É um texto autoral versionado que se acumula do Curso até o alvo. Uma interpretação estruturada pode organizar diretivas sem substituir o texto humano.",does:"A pessoa escreve ou revisa a orientação naquele escopo e pode solicitar/consultar a interpretação estruturada.",after:"A materialização recebe a orientação efetiva aplicável ao alvo junto dos parâmetros e da política de componentes.",why:"O texto humano permanece primeiro. A interpretação fica recolhida porque é ferramenta de trabalho, não substituto do enunciado original.",evidence:["docs/guia-professor-autor.md"]}),
  "author-components":screen({journey:"autoria",title:"12. Definir política de componentes",path:"Autoria › Escopo › Componentes didáticos",badges:[E,P],phone:`${header("Componentes")}${card("Disponibilidade",'<label class="row"><input type="radio" checked> Biblioteca completa</label><label class="row"><input type="radio"> Somente selecionados</label>')}${field("Buscar",'<input placeholder="Ex.: comparar relações, responder escolha…">')}${chips([["paragraph",true],["table",false],["formula",false],["chart",false],["flow",false],["choice-response",false],["gap-response",false],["… 25 outros",false]])}${card("Preferidos",'<p class="muted">Ajudam na escolha entre candidatos adequados.</p>')}${card("Excluídos",'<p class="muted">Exclusão prevalece sobre permissão e preferência.</p>')}`,what:"É a política que limita ou orienta o catálogo de 32 componentes didáticos do AraLearn.",does:"A pessoa deixa todo o catálogo disponível ou limita a uma lista; também pode marcar componentes excluídos e preferidos.",after:"A materialização recebe a política efetiva e registra o que foi aplicado.",why:"O catálogo não precisa ocupar a tela inteira. Busca por intenção e descoberta progressiva reduzem carga sem retirar capacidade.",evidence:["src/domain/courseDesignParameters.js","src/components/registry.js","docs/guia-professor-autor.md"]}),
  "author-sources":screen({journey:"autoria",title:"13. Organizar Fontes",path:"Autoria › Curso › Fontes",badges:[E,P,S],phone:`${header("Fontes","←","＋")}${field("Buscar",'<input placeholder="Título, autoria, identificador…">')}${card("Fonte de exemplo",'<p class="muted">Livro · revisão 2 · verificada</p>'+chips([["3 âncoras",false],["1 PDF",false],["Citação no Estudo",false]])+button("Abrir",true))}${card("Fonte pendente de identificação",'<p class="muted">Referência legada preservada; permanece oculta no Estudo até comprovação.</p>')}`,what:"É o catálogo privado e versionado de Fontes do Curso.",does:"A pessoa cria revisões, aposenta Fontes, pesquisa e abre detalhes. Metadados incluem tipo, título, autoria, data, identificador, idioma, citação, URL, edição/versão, origem, disponibilidade, verificação e visibilidade em Estudo.",after:"No detalhe, a pessoa gerencia Âncoras, PDFs, Observações da Fonte e atribuições a alvos.",why:"A lista fica simples; revisão, âncoras, PDFs e proveniência aparecem somente ao abrir a Fonte ou o alvo.",evidence:["docs/guia-professor-autor.md"]}),
  "author-source-detail":screen({journey:"autoria",title:"14. Ancorar e atribuir uma Fonte",path:"Autoria › Fontes › Fonte › Âncoras / PDFs / atribuição",badges:[E,P,S],phone:`${header("Fonte de exemplo")}${card("Revisão 2",'<p class="muted">Verificada · Mostrar citação no Estudo</p>')}${card("Âncora",'<p>Páginas 42–47</p><p class="muted">Trecho de verificação privado</p>'+button("Editar Âncora"))}${card("PDF privado",'<p class="muted">1 anexo · 6,2 MiB</p>'+button("Baixar"))}${card("Usar nesta Unidade",'<select><option>Sustenta o conteúdo</option><option>Informou</option><option>Adaptado de</option><option>Citação direta</option><option>Contrasta</option><option>Exemplifica</option><option>Inspirou</option><option>Precisa de verificação</option></select>'+button("Definir fontes",true))}`,what:"É o detalhe versionado de uma Fonte e a forma de ligá-la a um alvo com Âncora exata e relação explícita.",does:"A pessoa cria/edita Âncoras por páginas, tempo, fragmento URI ou citação textual; pode anexar PDFs e escolher como a Fonte participa de item do plano ou Unidade.",after:"Salvar a atribuição substitui o conjunto completo e ordenado daquele alvo. A proveniência pode ser exportada em JSON quando não há rascunho não salvo.",why:"Separar catálogo, detalhe e atribuição evita colocar metadados bibliográficos, PDFs e relações na mesma tela principal.",evidence:["docs/guia-professor-autor.md"],note:"Limites: até 8 PDFs por revisão de Fonte, 20 MiB por arquivo e 64 MiB de conteúdo PDF único por Curso."}),
  "author-structure":screen({journey:"autoria",title:"15. Conferir a estrutura",path:"Autoria › Curso › Estrutura",badges:[E,P,S],phone:`${header("Estrutura")}${card("Módulo 1 · Redes e comunicação",button("Lição 1 · O que é uma rede")+button("Lição 2 · Camadas e protocolos"))}${card("Módulo 2 · Endereçamento",button("Lição 1 · IPv4 e IPv6"))}`,what:"É uma leitura compacta e paginada da hierarquia do Curso.",does:"A pessoa percorre Módulos, Lições e Microssequências e vê identidade, posição, título e resumo.",after:"Pode abrir o contexto correspondente ou seguir para Inspeção das Unidades produzidas.",why:"Estrutura responde “como o Curso está organizado”; Inspeção responde “o que foi produzido”. Mantemos essas perguntas separadas.",evidence:["docs/guia-professor-autor.md"]}),
  "author-materialization":screen({journey:"autoria",title:"16. Produzir ou retomar uma Parte",path:"Autoria › Parte › Materialização",badges:[E,P,S],phone:`${header("Parte 3")} ${card("Materialização",'<div class="row between"><strong>2 de 5 etapas</strong><span>40%</span></div><div class="meter"><span style="width:40%"></span></div><p>✓ Contexto</p><p>✓ Microssequência 1</p><p>● Microssequência 2</p><p class="muted">○ Microssequência 3</p><p class="muted">○ Validação</p>')}${button("Retomar",true)}${button("Conferir conteúdo confirmado")}`,what:"É a execução persistida de produção de uma Parte. O servidor deriva o contexto efetivo de cada Microssequência: parâmetros, orientações, política de componentes, itens do plano e Fontes.",does:"A pessoa inicia ou retoma a execução e acompanha o progresso. O trabalho gerativo pode ser conduzido pelo cliente MCP; o AraLearn conserva estado e valida cada etapa.",after:"Cada etapa confirmada grava conteúdo, vínculo com Parte, proveniência, fatos de desenho, evento e recibo. Depois, a pessoa confere em Inspeção.",why:"A superfície humana mostra progresso e próxima ação; versões e mecanismos de concorrência ficam fora até serem necessários para diagnóstico.",evidence:["docs/criar-cursos-pelo-chat.md","supabase/migrations/*materialization*.sql"]}),
  "author-inspection":screen({journey:"autoria",title:"17. Conferir o conteúdo produzido",path:"Autoria › Curso › Inspeção",badges:[E,P,S],phone:`${header("Inspeção","←","⌄")}${field("Escopo",'<select><option>Parte 3 · Camadas de rede</option><option>Curso inteiro</option><option>Sem Parte</option><option>Módulo 1</option></select>')}${card("Unidade 1 · Por que protocolos existem?",'<p class="muted">Conteúdo renderizado como em Estudo; respostas de prática ficam inertes.</p><div class="footer-actions"><button class="icon">✎</button><button class="icon">✦</button><button class="icon">◌</button><button class="icon">⌑</button><button class="icon">✓</button></div>')}${card("Unidade 2",'<p class="muted">Carregada conforme a rolagem.</p>')}`,what:"É a leitura vertical das Unidades produzidas sob uma revisão do Curso.",does:"A pessoa escolhe escopo — Curso, Parte, sem Parte, Módulo, Lição ou Microssequência — e percorre o conteúdo no mesmo renderer do Estudo, com práticas inertes.",after:"De cada Unidade pode Editar, pedir Assistência por API, Anotar, Definir fontes ou Auditar.",why:"Depois de produzir uma Parte, esta deve ser uma das superfícies mais fáceis de alcançar: o autor naturalmente quer conferir o que foi gerado.",evidence:["docs/guia-professor-autor.md"]}),
  "author-observations":screen({journey:"autoria",title:"18. Tratar Observações",path:"Autoria › Revisar › Observações",badges:[E,P,S],phone:`${header("Observações")}<div class="row"><button class="button">Filtros</button><button class="button">Curso inteiro</button></div>${card("Possível erro",'<p class="muted">Estudante 7A3F · Unidade “Por que protocolos existem?”</p><p>O exemplo parece contradizer a definição anterior.</p>'+button("Abrir",true))}${card("No detalhe",'<p class="muted">Editar categoria/texto autoral · considerar · responder · resolver · reabrir · retirar · corrigir assuntos.</p>')}`,what:"É a caixa autoral das Anotações ancoradas que precisam de triagem.",does:"A pessoa filtra por origem, canal, estado, categoria, assunto e hierarquia; abre um registro, responde ou muda seu estado conforme permitido.",after:"Responder/resolver organiza a triagem. Se o conteúdo do Curso precisar mudar, a correção acontece por uma operação autoral própria, especialmente o ciclo de auditoria/correção.",why:"Separar Observações de Achados evita confundir manifestação humana com diagnóstico/correção do conteúdo.",evidence:["docs/guia-professor-autor.md"]}),
  "author-audit":screen({journey:"autoria",title:"19. Auditar, corrigir e verificar",path:"Autoria › Revisar › Achados",badges:[E,P,S],phone:`${header("Achado")}${card("Possível problema factual",'<p class="muted">Critério: evidência factual · aberto</p><p>A afirmação exige Fonte e Âncora ativas na revisão exata.</p>')}${button("Propor correção",true)}${card("Correção proposta",'<p class="muted">Antes → Depois · Fontes propostas</p>'+button("Confirmar aplicação",true))}${card("Depois de aplicar",'<p class="muted">Nova rodada de verificação → Resolver ou Manter aberto. Reversão exige que o estado aplicado ainda seja corrente.</p>')}`,what:"É o fluxo formal para investigar e corrigir uma Unidade de forma rastreável.",does:"A pessoa escolhe uma Unidade focal, registra/consulta rodada e achados, prepara uma proposta de correção e confirma a aplicação depois de compreender o efeito.",after:"Outra rodada verifica o critério. Só um resultado aprovado permite resolver; caso contrário, o achado permanece aberto. A reversão é condicionada ao estado corrente.",why:"O fluxo deixa explícito que “editar rápido” e “corrigir com trilha auditável” são usos diferentes.",evidence:["docs/guia-professor-autor.md","src/domain/courseAuditCycle.js"],note:"Para conclusão factual positiva, o contrato exige Fonte e Âncora ativas na revisão exata."}),
  "author-variants":screen({journey:"autoria",title:"20. Criar variantes comparáveis",path:"Autoria › Curso › Variantes",badges:[E,P,S],phone:`${header("Variantes","←","＋")}${card("Comparação A",'<p class="muted">Ponto comum: planejamento atual</p><div class="split"><div class="mini"><strong>Referência</strong><p class="muted">Prática: 2 oportunidades</p></div><div class="mini"><strong>Variante B</strong><p class="muted">Prática: 3 oportunidades</p></div></div>'+button("Comparar",true))}<table class="table"><tr><th>Aspecto</th><th>Ref.</th><th>B</th></tr><tr><td>Oportunidades</td><td>2</td><td>3</td></tr><tr><td>Drift não declarado</td><td>—</td><td>0</td></tr></table>`,what:"Variantes criam de 2 a 8 Cursos independentes a partir de um checkpoint do planejamento. Não são versões sucessivas de um mesmo Curso.",does:"A pessoa cria um conjunto, define uma variante de referência e declara em pelo menos outra uma diferença intencional de parâmetro ou política de componentes.",after:"Cada Curso materializa suas próprias Unidades. A comparação mostra ponto comum, diferenças declaradas, fatos materializados, drift e dados ausentes. Desvincular preserva os Cursos.",why:"A tela chama de Variantes, não “versões”, para evitar confundir comparação experimental/descritiva com histórico de edição.",evidence:["docs/guia-professor-autor.md","src/domain/courseVariants.js"]}),
  "author-research":screen({journey:"autoria",title:"21. Examinar fatos de Autoria",path:"Autoria › Curso › Pesquisa",badges:[E,P,S],phone:`${header("Pesquisa","←","⇩")}${field("Conjunto",'<select><option>Materializações</option><option>Atividade</option><option>Desenho</option><option>Fontes</option><option>Observações</option><option>Auditorias</option><option>Variantes</option></select>')}${card("Fatos por tipo",'<div style="height:130px;display:flex;gap:12px;align-items:end"><div style="height:60%;width:25%;background:#dfe3f7"></div><div style="height:90%;width:25%;background:#dfe3f7"></div><div style="height:40%;width:25%;background:#dfe3f7"></div></div>'+button("Ver tabela equivalente"))}${card("Definição da métrica",'<p class="muted">Denominador · filtros · dados ausentes · limites de interpretação.</p>')}${card("Fatos",'<p class="muted">Lista paginada com links para os objetos de origem.</p>')}`,what:"É a área de analytics do processo de Autoria, não um construtor completo de experimento educacional.",does:"A pessoa escolhe um dos 7 conjuntos — atividade, materializações, desenho, Fontes, Observações, auditorias e variantes — aplica filtros, lê gráfico/tabela/fatos e exporta CSV ou JSON.",after:"Os deep links levam aos objetos que originaram os fatos. A interpretação deve respeitar definição, denominador e dados ausentes.",why:"Gráfico e tabela são duas representações do mesmo recorte; métricas ficam acompanhadas de definição para evitar leitura causal indevida.",evidence:["docs/guia-professor-autor.md","src/domain/courseAuthoringAnalytics.js"]}),
  "author-people":screen({journey:"autoria",title:"22. Conceder acesso ao Estudo",path:"Autoria › Curso › Pessoas",badges:[E,P,S],phone:`${header("Pessoas","←","＋")}${card("Você",'<p class="muted">Proprietário</p>')}${card("Marina S.",'<p class="muted">Acesso ao Estudo</p>'+button("Revogar acesso"))}${button("Conceder acesso por e-mail",true)}`,what:"É a gestão de quem pode estudar o Curso. O modelo corrente tem um proprietário e acesso direto de outras pessoas ao Estudo.",does:"O proprietário concede ou revoga acesso ao Estudo. Nome e foto aparecem quando a relação permite.",after:"A pessoa com acesso passa a ver o Curso no Estudo, mas não vira coautora do original. Se editar uma Unidade, a primeira gravação material cria uma cópia pessoal privada.",why:"Pessoas fica no contexto do Curso, porque a relação é acesso àquele Curso, não uma administração global de usuários.",evidence:["docs/guia-professor-autor.md"]}),

  "mcp-composer":screen({journey:"mcp",title:"1. Preparar um pedido no AraLearn",path:"Autoria › Alvo › ChatGPT",badges:[E,P,S],phone:`${header("ChatGPT")} ${card("Alvo",'<p><strong>Parte 3 · Camadas de rede</strong></p><p class="muted">Curso › Planejamento › Parte 3</p>')}${field("Intenção",'<select><option>Produzir esta Parte</option><option>Revisar</option><option>Discutir</option></select>')}${field("Pedido",'<textarea rows="6">Produza esta Parte respeitando planejamento, parâmetros e Fontes aplicáveis.</textarea>')}${button("Copiar pedido",true)}<div class="good">Copiar não altera o Curso.</div>`,what:"É a ponte contextual entre a Autoria visual e um cliente MCP externo. O AraLearn não executa o pedido ao copiar.",does:"A pessoa confere alvo/caminho, escolhe intenção, ajusta o texto e copia o pedido preparado.",after:"A geração e as chamadas MCP acontecem no ChatGPT ou em outro cliente compatível que a pessoa tenha conectado.",why:"O alvo nasce do contexto visual. Assim a pessoa não precisa copiar IDs, revisão ou caminho manualmente.",evidence:["docs/autoria-mcp.md","docs/criar-cursos-pelo-chat.md"]}),
  "mcp-connect":screen({journey:"mcp",title:"2. Autorizar o cliente MCP",path:"Cliente MCP › OAuth › AraLearn",badges:[E,P],phone:`${header("Autorizar cliente")} ${card("AraLearn",'<p>O cliente solicita acesso MCP à sua conta.</p><p class="muted">Escopo: offline_access</p>')}${button("Autorizar",true)}${button("Cancelar")}`,what:"É a autorização OAuth 2.1/PKCE do cliente MCP contra a conta individual do AraLearn.",does:"A pessoa autoriza o cliente compatível. O MCP continua sujeito à propriedade do Curso e às permissões do AraLearn.",after:"O cliente descobre as ferramentas e o recurso de invariantes e pode operar Cursos próprios.",why:"O atlas mostra o fluxo de autorização, mas não inventa uma tela específica do ChatGPT. O repositório comprova protocolo/OAuth, não que um app do AraLearn esteja publicado ou instalável na interface corrente do ChatGPT.",evidence:["src/ui/OAuthAuthorizationConsent.js","docs/autoria-mcp.md","docs/criar-cursos-pelo-chat.md"]}),
  "mcp-tools":screen({journey:"mcp",title:"3. Entender as cinco ferramentas",path:"Cliente MCP › Ferramentas do AraLearn",badges:[E,P],phone:`${header("Ferramentas MCP","×")} ${card("listarCursos",'<p class="muted">Localiza Cursos próprios.</p>')}${card("lerCurso",'<p class="muted">Lê plano, desenho, Fontes, inspeção, auditoria, variantes, Pesquisa, materialização etc.</p>')}${card("criarCurso",'<p class="muted">Cria Curso privado vazio.</p>')}${card("alterarCurso",'<p class="muted">Aplica operações autorais fechadas e idempotentes.</p>')}${card("consultarComponentesDidaticos",'<p class="muted">Explora, pesquisa, inspeciona, valida e pré-visualiza componentes.</p>')}`,what:"A revisão-âncora expõe cinco ferramentas autorais MCP. O cliente escolhe a ferramenta conforme a intenção; não recebe acesso livre ao banco.",does:"Normalmente o cliente começa listando/localizando o Curso e lendo a vista pertinente antes de alterar.",after:"Para produzir uma Parte, ele lê plano, desenho, Fontes e componentes necessários e então usa a operação de alteração/materialização apropriada.",why:"Mostramos o pequeno catálogo para você entender o papel do MCP. Perfil, Pessoas e criação da cópia pessoal são capacidades exclusivas da aplicação, não ferramentas MCP autorais.",evidence:["supabase/functions/_shared/aralearn-authoring/courseMcpTools.js","docs/autoria-mcp.md"]}),
  "mcp-plan":screen({journey:"mcp",title:"4. Ler o contexto antes de produzir",path:"Cliente MCP › Parte 3 › Preparação",badges:[E,P,S],phone:`${header("Preparação MCP","×")} ${card("1. Localizar Curso",'<p class="muted">listarCursos → escolher o Curso correto</p>')}${card("2. Ler planejamento",'<p class="muted">lerCurso · instructional_plan</p>')}${card("3. Ler desenho",'<p class="muted">lerCurso · course_design no escopo pertinente</p>')}${card("4. Ler Fontes",'<p class="muted">lerCurso · course_sources</p>')}${card("5. Descobrir componentes",'<p class="muted">consultarComponentesDidaticos progressivamente</p>')}`,what:"É a sequência conceitual que dá ao cliente o contexto necessário para produzir sem inventar estado.",does:"O cliente relê Curso, revisão, Parte, desenho, Fontes e catálogo necessário. Quando falta informação, deve explicitar a lacuna ou pedir esclarecimento.",after:"Com contexto suficiente, inicia a materialização da Parte. O servidor ainda deriva e sela o contexto confiável de cada Microssequência.",why:"A conversa não vira uma cópia escondida do Curso. O estado corrente é relido sob demanda.",evidence:["docs/criar-cursos-pelo-chat.md","docs/autoria-mcp.md"]}),
  "mcp-materialize":screen({journey:"mcp",title:"5. Iniciar a materialização",path:"Cliente MCP › Parte 3 › Materialização",badges:[E,P,S],phone:`${header("Materialização MCP","×")} ${card("Execução criada",'<p class="muted">Contexto persistido · 5 etapas · próxima: Microssequência 1</p>')}${card("Contexto efetivo",chips([["parâmetros",true],["orientação",true],["componentes",true],["plano",true],["Fontes",true]]))}${button("Produzir próxima etapa",true)}`,what:"É o início da execução persistida. O servidor deriva os dados efetivos do alvo e não aceita que o cliente simplesmente declare o contexto como confiável.",does:"O cliente lê a execução e identifica a próxima etapa pendente.",after:"Passa a produzir uma Microssequência por vez, dentro do recorte autorizado.",why:"A persistência por etapas permite retomar em outra conversa sem depender do histórico do chat.",evidence:["docs/criar-cursos-pelo-chat.md","docs/autoria-mcp.md"]}),
  "mcp-step":screen({journey:"mcp",title:"6. Produzir e confirmar cada etapa",path:"Cliente MCP › Materialização › Microssequência",badges:[E,P,S],phone:`${header("Microssequência 2","×")} ${card("Produzir",'<p class="muted">Somente o recorte autorizado desta Microssequência.</p>')}${card("Validar",'<p class="muted">Hierarquia · conteúdo · contratos de componentes · Fontes aplicáveis.</p>')}${card("Aplicar",'<p class="muted">Enviar lote com revisões/versões esperadas.</p>')}${card("Reler",'<p class="muted">Informar apenas o que o servidor confirmou.</p>')}${button("Próxima etapa",true)}`,what:"É o ciclo repetido para cada Microssequência da Parte.",does:"O cliente produz, valida, declara fatos de desenho, aplica Fontes permitidas, envia a alteração e relê o resultado confirmado.",after:"A transação confirma entidades, vínculo com Parte, proveniência, progresso, evento e recibo. Se a validação falha, a etapa é revertida. Depois segue para a próxima ou para validação final.",why:"O fluxo mostra claramente que “o modelo gerou texto” não significa “o Curso foi alterado”: só a confirmação do AraLearn muda o estado.",evidence:["docs/criar-cursos-pelo-chat.md"]}),
  "mcp-return":screen({journey:"mcp",title:"7. Voltar ao AraLearn e conferir",path:"ChatGPT / cliente MCP › AraLearn › Parte 3",badges:[E,P,S],phone:`${header("Parte 3")}<div class="good"><strong>Alterações confirmadas detectadas</strong><br><span class="muted">A área visível foi relida ao retornar.</span></div>${card("Parte materializada",'<p class="muted">3 Microssequências · validação concluída</p>')}${button("Conferir em Inspeção",true)}<div class="split">${button("Parâmetros aplicados")}${button("Fontes")}</div>${button("Revisar / Auditar")}`,what:"É o retorno ao mesmo Curso vivo depois de uma operação MCP confirmada.",does:"A pessoa confere o resultado produzido: conteúdo, desenho aplicado, Fontes e eventuais divergências. O AraLearn relê ao voltar/focar a janela ou por ação explícita de atualização.",after:"Se estiver satisfatório, continua a produção. Se encontrar problema, pode editar manualmente, observar ou usar auditoria/correção.",why:"Esta é uma melhoria de UX especialmente importante: depois de geração automática, o próximo trabalho humano natural é conferir. O atlas propõe deixar essa conferência imediatamente acessível.",evidence:["docs/autoria-mcp.md","docs/criar-cursos-pelo-chat.md"]}),

  settings:screen({journey:"conta",title:"1. Conta e aparência",path:"AraLearn › Conta e aparência",badges:[E,P],phone:`${header("Conta e aparência")}${card("Perfil",button("Nome e avatar"))}${card("Aparência",button("Tema"))}${card("Dados neste dispositivo",button("Remover dados locais"))}${card("Sessão",button("Sair")+button("Sair e remover dados locais"))}${card("Conta",button("Excluir conta"))}`,what:"É a área para perfil, aparência, sessão e ciclo de dados locais/remotos.",does:"A pessoa pode ajustar perfil/avatar e tema e escolher entre logout comum, limpeza local, logout com limpeza local ou exclusão irreversível da conta.",after:"Ações destrutivas exigem confirmação e respeitam a distinção entre dados locais, sessão e exclusão remota.",why:"Agrupamos por efeito sobre a pessoa e seus dados, não por detalhes técnicos de armazenamento.",evidence:["CHANGELOG.md","docs/privacidade.md"]})
};

const els={
  journeyName:document.querySelector("#journeyName"),screenTitle:document.querySelector("#screenTitle"),screenPath:document.querySelector("#screenPath"),badges:document.querySelector("#badges"),phone:document.querySelector("#phone"),what:document.querySelector("#what"),does:document.querySelector("#does"),after:document.querySelector("#after"),why:document.querySelector("#why"),whySection:document.querySelector("#whySection"),related:document.querySelector("#related"),evidence:document.querySelector("#evidence"),prev:document.querySelector("#prevButton"),next:document.querySelector("#nextButton"),counter:document.querySelector("#counter"),map:document.querySelector("#mapOverlay"),mapContents:document.querySelector("#mapContents")
};
let currentId="login";

function journeyPosition(id){
  const s=screens[id]; const j=journeys[s.journey]; return {j,index:j.ids.indexOf(id)};
}
function badgeClass(value){return value;}
function render(id,{push=true}={}){
  if(!screens[id]) return;
  currentId=id;
  const s=screens[id],{j,index}=journeyPosition(id);
  els.journeyName.textContent=j.label;
  els.screenTitle.textContent=s.title;
  els.screenPath.textContent=s.path;
  els.badges.innerHTML=s.badges.map(b=>`<span class="badge ${badgeClass(b)}">${badgeLabels[b]}</span>`).join("");
  els.phone.innerHTML=s.phone;
  els.what.textContent=s.what;
  els.does.textContent=s.does;
  els.after.textContent=s.after;
  els.whySection.hidden=!s.why;
  els.why.textContent=s.why||"";
  els.related.innerHTML=(s.related||[]).map(r=>`<button type="button" data-jump="${r}">${screens[r].title}</button>`).join("");
  els.evidence.innerHTML=(s.evidence||[]).map(p=>`<div><code>${p}</code></div>`).join("")+(s.note?`<p>${s.note}</p>`:"");
  els.prev.disabled=index===0;
  els.next.disabled=index===j.ids.length-1;
  els.counter.textContent=`${j.label} · ${index+1} de ${j.ids.length}`;
  document.querySelectorAll("[data-journey]").forEach(b=>b.classList.toggle("active",b.dataset.journey===s.journey));
  document.querySelectorAll("[data-jump]").forEach(b=>b.addEventListener("click",()=>render(b.dataset.jump)));
  if(push) history.replaceState(null,"",`#${id}`);
  window.scrollTo({top:0,behavior:"instant"});
}
function step(delta){
  const {j,index}=journeyPosition(currentId); const target=j.ids[index+delta]; if(target) render(target);
}
els.prev.addEventListener("click",()=>step(-1));
els.next.addEventListener("click",()=>step(1));
document.querySelectorAll("[data-journey]").forEach(b=>b.addEventListener("click",()=>render(journeys[b.dataset.journey].ids[0])));

function buildMap(){
  els.mapContents.innerHTML=Object.entries(journeys).map(([key,j])=>`<section class="map-group"><h3>${j.label}</h3>${j.ids.map(id=>`<button type="button" data-map-jump="${id}">${screens[id].title}</button>`).join("")}</section>`).join("");
  document.querySelectorAll("[data-map-jump]").forEach(b=>b.addEventListener("click",()=>{els.map.hidden=true;render(b.dataset.mapJump);}));
}
document.querySelector("#mapButton").addEventListener("click",()=>{buildMap();els.map.hidden=false;});
document.querySelector("#closeMap").addEventListener("click",()=>els.map.hidden=true);
els.map.addEventListener("click",e=>{if(e.target===els.map) els.map.hidden=true;});
document.addEventListener("keydown",e=>{if(e.key==="Escape") els.map.hidden=true; if(e.key==="ArrowRight"&&!els.map.hidden) return; if(e.key==="ArrowRight"&&els.map.hidden) step(1); if(e.key==="ArrowLeft"&&els.map.hidden) step(-1);});

const initial=location.hash.slice(1);
render(screens[initial]?initial:"login",{push:false});
