export const COURSE_FORGE_PATCH_TYPE = "aralearn.structure.patch.v1";

export const COURSE_FORGE_PHASE_IDS = Object.freeze([
  "normalize_intent",
  "index_sources",
  "build_assessment_profile",
  "plan_architecture",
  "audit_architecture",
  "repair_architecture",
  "plan_lessons",
  "build_course_graph",
  "audit_course_graph",
  "repair_course_graph",
  "build_lesson_governance",
  "plan_microsequences",
  "audit_microsequences",
  "repair_microsequences",
  "build_microsequence_contract",
  "compile_card_plans",
  "build_cards",
  "audit_cards",
  "audit_source_adherence",
  "repair_cards",
  "repair_card_adherence",
  "audit_prerequisites",
  "audit_assessment_alignment",
  "compile_patch",
  "validate_patch",
  "apply_patch",
  "final_report"
]);
