import { escapePackageAttribute, renderPackageProse } from "../../sdk/html.js";

function pair(value) { return Array.isArray(value) && value.length === 2 ? value.map(Number) : null; }
function collectVectors(data) { return [data.vector, ...(data.vectors || []), ...(data.sum || []), ...(data.distance || [])].map(pair).filter((value) => value?.every(Number.isFinite)); }
function planeAccessibleText(data) { return `${data.prompt || "Plano cartesiano."} ${collectVectors(data).map((value, index) => `Vetor ${index + 1}: (${value.join(", ")})`).join(". ")}`; }

export const planePackage = Object.freeze({
  manifest: Object.freeze({ id: "aralearn.resource.plane", version: "1.0.0", label: "Plano cartesiano", purpose: "Situar pontos e vetores em duas dimensões e tornar operações geométricas observáveis.", slots: Object.freeze(["content", "feedback"]), cognitiveOperations: Object.freeze(["locate-coordinate", "add-vector", "measure-distance", "inspect-direction"]), responseCompatibility: Object.freeze(["aralearn.response.gap", "aralearn.response.choice"]), limitations: Object.freeze(["Somente duas dimensões.", "Não use quando a operação é puramente algébrica." ]), accessibility: "Todos os pontos e vetores são descritos por coordenadas em texto." }),
  authoringContract: Object.freeze({ intent: "Declare pontos ou vetores; o motor escolhe escala e desenho.", required: Object.freeze([]), optional: Object.freeze(["prompt", "x", "y", "vector", "vectors", "sum", "distance", "result"]), rules: Object.freeze(["Declare ao menos uma operação geométrica."]), example: Object.freeze({ prompt: "Observe o vetor.", vector: [2, 1] }) }),
  schema: Object.freeze({ type: "object", additionalProperties: false, properties: { prompt: { type: "string" }, x: { type: "array", minItems: 2, maxItems: 2, items: { type: "number" } }, y: { type: "array", minItems: 2, maxItems: 2, items: { type: "number" } }, vector: { type: "array", minItems: 2, maxItems: 2, items: { type: "number" } }, vectors: { type: "array", items: { type: "array", minItems: 2, maxItems: 2, items: { type: "number" } } }, sum: { type: "array", items: { type: "array", minItems: 2, maxItems: 2, items: { type: "number" } } }, distance: { type: "array", minItems: 2, maxItems: 2, items: { type: "array", minItems: 2, maxItems: 2, items: { type: "number" } } }, result: { anyOf: [{ type: "string" }, { type: "array", minItems: 2, maxItems: 2, items: { type: "number" } }] } } }),
  normalize(data) { const copyPair = (value) => value ? value.map(Number) : undefined; return { ...(data?.prompt ? { prompt: String(data.prompt).trim() } : {}), ...Object.fromEntries(["x", "y", "vector"].filter((key) => data?.[key]).map((key) => [key, copyPair(data[key])])), ...Object.fromEntries(["vectors", "sum", "distance"].filter((key) => data?.[key]).map((key) => [key, data[key].map(copyPair)])), ...(data?.result !== undefined ? { result: Array.isArray(data.result) ? copyPair(data.result) : String(data.result) } : {}) }; },
  validate(data) { return collectVectors(data).length || data.x || data.y ? [] : ["Plane precisa de ponto ou vetor."]; },
  render(data) { const vectors = collectVectors(data); const max = Math.max(1, ...vectors.flatMap((value) => value.map(Math.abs))); const point = ([x, y]) => [50 + (x / max) * 38, 50 - (y / max) * 38]; return `<div class="runtime-block runtime-plane-block">${data.prompt ? renderPackageProse(data.prompt) : ""}<svg class="package-plane" viewBox="0 0 100 100" role="img" aria-label="${escapePackageAttribute(planeAccessibleText(data))}"><line x1="8" y1="50" x2="92" y2="50"/><line x1="50" y1="92" x2="50" y2="8"/>${vectors.map((vector, index) => { const [x, y] = point(vector); return `<line class="package-plane-vector tone-${index % 4}" x1="50" y1="50" x2="${x}" y2="${y}"/><circle cx="${x}" cy="${y}" r="2"/>`; }).join("")}</svg></div>`; },
  accessibleText(data) { return planeAccessibleText(data); }, editableTargets() { return []; }
});
