import { academicProfile } from "../../sdk/academic.js";
import { escapePackageAttribute, renderPackageInline, renderPackageProse } from "../../sdk/html.js";

function membershipKey(ids) { return [...ids].sort().join("+"); }

export const setDiagramPackage = Object.freeze({
  manifest: Object.freeze({ id: "aralearn.resource.set_diagram", version: "1.0.0", label: "Diagrama de conjuntos", purpose: "Representar inclusão, exclusão e interseção entre dois ou três conjuntos, preservando as regiões de um diagrama de Venn/Euler.", slots: Object.freeze(["content", "feedback"]), cognitiveOperations: Object.freeze(["inspect-intersection", "classify-membership", "compare-sets", "apply-set-operation"]), academic: academicProfile({ domains: ["teoria dos conjuntos", "lógica", "probabilidade", "bancos de dados"], knowledgeObjects: ["conjunto", "interseção", "união", "complemento", "região"], conventions: ["contorno por conjunto", "interseções por sobreposição", "universo explícito quando necessário", "elementos vinculados à região exata"], appropriateWhen: ["pertencimento simultâneo ou operações entre conjuntos são parte da tarefa"], avoidWhen: ["a relação é entre elementos de dois conjuntos sem interseção", "há mais de três conjuntos relevantes"], technologies: ["SVG responsivo", "lista semântica de regiões"], practiceModes: ["exposition", "gap", "typing", "selection", "classification"] }), responseCompatibility: Object.freeze(["aralearn.response.gap", "aralearn.response.choice"]), limitations: Object.freeze(["No máximo três conjuntos por card.", "Regiões com texto longo usam a legenda, não texto dentro das curvas."]), accessibility: "As regiões são enumeradas por pertencimento; o desenho não é a única fonte de informação." }),
  authoringContract: Object.freeze({ intent: "Declare conjuntos e regiões por ids de pertencimento; não declare coordenadas nem elipses.", required: Object.freeze(["sets", "regions"]), optional: Object.freeze(["prompt", "universeLabel"]), rules: Object.freeze(["Cada region.setIds contém ids existentes e sem repetição.", "Regiões semanticamente iguais não se repetem.", "Use relation_map para pares entre domínio e contradomínio.", "Use no máximo três conjuntos; para muitas categorias, prefira classificação ou outra representação analítica."]), example: Object.freeze({ prompt: "Classifique as linguagens por paradigma e observe as interseções; os nomes ficam na legenda das regiões para não sobrecarregar o desenho.", universeLabel: "Linguagens analisadas", sets: [{ id: "imperative", label: "Imperativas" }, { id: "object", label: "Orientadas a objetos" }, { id: "functional", label: "Funcionais" }], regions: [{ id: "all", setIds: ["imperative", "object", "functional"], label: "Multiparadigma nos três grupos", items: ["Python", "Scala"] }, { id: "imperative-object", setIds: ["imperative", "object"], label: "Imperativa e orientada a objetos", items: ["Java"] }, { id: "functional-only", setIds: ["functional"], label: "Funcional neste recorte", items: ["Haskell"] }, { id: "outside", setIds: [], label: "Fora dos três critérios", items: ["SQL declarativa"] }] }) }),
  schema: Object.freeze({ type: "object", additionalProperties: false, required: ["sets", "regions"], properties: { prompt: { type: "string" }, universeLabel: { type: "string" }, sets: { type: "array", minItems: 2, maxItems: 3, items: { type: "object", additionalProperties: false, required: ["id", "label"], properties: { id: { type: "string", minLength: 1 }, label: { type: "string", minLength: 1 } } } }, regions: { type: "array", minItems: 1, maxItems: 8, items: { type: "object", additionalProperties: false, required: ["id", "setIds", "items"], properties: { id: { type: "string", minLength: 1 }, setIds: { type: "array", maxItems: 3, uniqueItems: true, items: { type: "string", minLength: 1 } }, label: { type: "string" }, items: { type: "array", items: { type: "string", minLength: 1 } } } } } } }),
  normalize(data) { return { ...(data?.prompt ? { prompt: String(data.prompt).trim() } : {}), ...(data?.universeLabel ? { universeLabel: String(data.universeLabel).trim() } : {}), sets: (data?.sets || []).map((set) => ({ id: String(set?.id || "").trim(), label: String(set?.label || "").trim() })), regions: (data?.regions || []).map((region) => ({ id: String(region?.id || "").trim(), setIds: (region?.setIds || []).map(String), ...(region?.label ? { label: String(region.label).trim() } : {}), items: (region?.items || []).map(String) })) }; },
  validate(data) { const sets = new Set(data.sets.map(({ id }) => id)); const keys = data.regions.map(({ setIds }) => membershipKey(setIds)); const errors = []; if (sets.size !== data.sets.length) errors.push("Conjuntos precisam de ids únicos."); if (data.regions.some(({ setIds }) => setIds.some((id) => !sets.has(id)))) errors.push("Região referencia conjunto inexistente."); if (new Set(keys).size !== keys.length) errors.push("Cada combinação de pertencimento pode aparecer uma única vez."); return errors; },
  render(data) { const setById = new Map(data.sets.map((set) => [set.id, set])); const ellipses = data.sets.length === 2 ? ['<ellipse cx="42" cy="50" rx="31" ry="32"/>', '<ellipse cx="78" cy="50" rx="31" ry="32"/>'] : ['<ellipse cx="43" cy="42" rx="29" ry="30"/>', '<ellipse cx="77" cy="42" rx="29" ry="30"/>', '<ellipse cx="60" cy="70" rx="29" ry="30"/>']; return `<div class="runtime-block package-set-diagram">${data.prompt ? renderPackageProse(data.prompt) : ""}<figure><div class="package-set-canvas"><svg viewBox="0 0 120 104" role="img" aria-label="${escapePackageAttribute(data.sets.map(({ label }) => label).join(", "))}">${ellipses.map((shape, index) => `<g class="tone-${index}">${shape}</g>`).join("")}</svg><div class="package-set-labels">${data.sets.map((set, index) => `<span class="tone-${index}">${renderPackageInline(set.label)}</span>`).join("")}</div></div><figcaption>${data.universeLabel ? `<strong>Universo: ${renderPackageInline(data.universeLabel)}</strong>` : ""}<ol>${data.regions.map((region) => `<li><span>${region.setIds.length ? region.setIds.map((id) => renderPackageInline(setById.get(id)?.label || id)).join(" ∩ ") : "Fora dos conjuntos"}</span>${region.label ? `<strong>${renderPackageInline(region.label)}</strong>` : ""}<small>${region.items.length ? region.items.map(renderPackageInline).join(", ") : "∅"}</small></li>`).join("")}</ol></figcaption></figure></div>`; },
  accessibleText(data) { const sets = new Map(data.sets.map((set) => [set.id, set.label])); return `${data.prompt || "Diagrama de conjuntos."} ${data.regions.map((region) => `${region.setIds.length ? region.setIds.map((id) => sets.get(id)).join(" e ") : "fora dos conjuntos"}: ${region.items.length ? region.items.join(", ") : "conjunto vazio"}`).join("; ")}.`; },
  editableTargets(data) { return [...(data.prompt ? [{ path: "prompt", label: "Editar orientação" }] : []), ...(data.universeLabel ? [{ path: "universeLabel", label: "Editar universo" }] : []), ...data.sets.map((_, index) => ({ path: `sets[${index}].label`, label: `Editar conjunto ${index + 1}` })), ...data.regions.flatMap((region, regionIndex) => [...(region.label ? [{ path: `regions[${regionIndex}].label`, label: `Editar região ${regionIndex + 1}` }] : []), ...region.items.map((_, itemIndex) => ({ path: `regions[${regionIndex}].items[${itemIndex}]`, label: `Editar elemento ${regionIndex + 1}.${itemIndex + 1}` }))])]; },
  practiceTargets(data) { return data.regions.flatMap((region, regionIndex) => region.items.map((_, itemIndex) => ({ path: `regions[${regionIndex}].items[${itemIndex}]`, label: `Lacuna no elemento ${regionIndex + 1}.${itemIndex + 1}`, modes: ["gap", "typing"] }))); }
});
