import { academicProfile } from "../../sdk/academic.js";
import { escapePackageAttribute, escapePackageHtml, renderPackageActionIcon, renderPackageInline, renderPackageProse } from "../../sdk/html.js";

function feedbackHtml(blockKey, feedback) {
  if (!feedback) return "";
  if (feedback === "correct") return '<div class="inline-feedback ok"><p class="tiny">Correto.</p></div>';
  if (feedback === "incomplete") return '<div class="inline-feedback warn"><p class="tiny">Complete todos os encaixes.</p></div>';
  const key = escapePackageAttribute(blockKey);
  return `<div class="inline-feedback err has-actions"><p class="tiny">Revise as correspondências.</p><div class="feedback-icons"><button class="icon-pill" type="button" data-action="matching-view-answer" data-response-block-key="${key}" title="Ver resposta" aria-label="Ver resposta">${renderPackageActionIcon("answer")}</button><button class="icon-pill primary" type="button" data-action="matching-try-again" data-response-block-key="${key}" title="Tentar de novo" aria-label="Tentar de novo">${renderPackageActionIcon("retry")}</button></div></div>`;
}

export const matchingResponsePackage = Object.freeze({
  manifest: Object.freeze({ id: "aralearn.response.matching", version: "1.0.0", label: "Encaixe de correspondências", purpose: "Pedir que o estudante encaixe cada item na correspondência ou categoria adequada.", slots: Object.freeze(["response"]), cognitiveOperations: Object.freeze(["match", "classify", "associate-function", "reconstruct-pairs"]), academic: academicProfile({ domains: ["transversal"], knowledgeObjects: ["correspondência", "categoria", "par"], conventions: ["cada origem permanece visível", "destinos nomeados", "alternativa acessível ao arraste"], appropriateWhen: ["reconstruir pares ou classificar itens é a evidência desejada"], avoidWhen: ["a ordem ou a produção livre é a operação central"], technologies: ["select HTML nativo", "controles acessíveis"], practiceModes: ["matching", "classification"], content: false }), responseCompatibility: Object.freeze([]), limitations: Object.freeze(["Não use para associações ambíguas sem critério explicitado.", "Mais de oito origens devem ser divididas."]), accessibility: "Cada origem possui um seletor nativo rotulado; arrastar nunca é obrigatório." }),
  authoringContract: Object.freeze({ intent: "Declare origens, destinos e o par correto; o estudante encaixa por controles nativos.", required: Object.freeze(["prompt", "leftItems", "rightItems", "answerPairs"]), optional: Object.freeze(["mode"]), rules: Object.freeze(["Cada origem aparece exatamente uma vez em answerPairs.", "Classification permite reutilizar destinos; one-to-one não."]), example: Object.freeze({ prompt: "Associe cada protocolo à camada.", mode: "classification", leftItems: [{ id: "tcp", label: "TCP" }, { id: "ip", label: "IP" }], rightItems: [{ id: "transport", label: "Transporte" }, { id: "network", label: "Rede" }], answerPairs: [{ leftId: "tcp", rightId: "transport" }, { leftId: "ip", rightId: "network" }] }) }),
  schema: Object.freeze({ type: "object", additionalProperties: false, required: ["prompt", "leftItems", "rightItems", "answerPairs"], properties: { prompt: { type: "string", minLength: 1 }, mode: { type: "string", enum: ["one-to-one", "classification"] }, leftItems: { type: "array", minItems: 2, maxItems: 8, items: { type: "object", additionalProperties: false, required: ["id", "label"], properties: { id: { type: "string", minLength: 1 }, label: { type: "string", minLength: 1 } } } }, rightItems: { type: "array", minItems: 2, maxItems: 8, items: { type: "object", additionalProperties: false, required: ["id", "label"], properties: { id: { type: "string", minLength: 1 }, label: { type: "string", minLength: 1 } } } }, answerPairs: { type: "array", minItems: 2, maxItems: 8, items: { type: "object", additionalProperties: false, required: ["leftId", "rightId"], properties: { leftId: { type: "string", minLength: 1 }, rightId: { type: "string", minLength: 1 } } } } } }),
  normalize(data) { return { prompt: String(data?.prompt || "").trim(), mode: String(data?.mode || "one-to-one"), leftItems: (data?.leftItems || []).map((item) => ({ id: String(item?.id || "").trim(), label: String(item?.label || "").trim() })), rightItems: (data?.rightItems || []).map((item) => ({ id: String(item?.id || "").trim(), label: String(item?.label || "").trim() })), answerPairs: (data?.answerPairs || []).map((pair) => ({ leftId: String(pair?.leftId || "").trim(), rightId: String(pair?.rightId || "").trim() })) }; },
  validate(data) { const left = new Set(data.leftItems.map(({ id }) => id)); const right = new Set(data.rightItems.map(({ id }) => id)); const answerLeft = data.answerPairs.map(({ leftId }) => leftId); const errors = []; if (left.size !== data.leftItems.length || right.size !== data.rightItems.length) errors.push("Itens precisam de ids únicos em cada lado."); if (data.answerPairs.some(({ leftId, rightId }) => !left.has(leftId) || !right.has(rightId))) errors.push("Resposta referencia item inexistente."); if (answerLeft.length !== left.size || new Set(answerLeft).size !== left.size) errors.push("Cada item de origem precisa de exatamente uma resposta."); if (data.mode === "one-to-one" && new Set(data.answerPairs.map(({ rightId }) => rightId)).size !== data.answerPairs.length) errors.push("One-to-one não permite reutilizar destinos."); return errors; },
  render(data, options = {}) { const blockKey = String(options.blockKey || options.instanceId || "package-matching"); const matches = options.responseState?.matches || {}; const rows = data.leftItems.map((left) => `<label><span>${renderPackageInline(left.label)}</span><select data-action="matching-set" data-response-block-key="${escapePackageAttribute(blockKey)}" data-matching-left-id="${escapePackageAttribute(left.id)}" aria-label="Correspondência para ${escapePackageAttribute(left.label)}"><option value="">Escolha…</option>${data.rightItems.map((right) => `<option value="${escapePackageAttribute(right.id)}"${String(matches[left.id] || "") === right.id ? " selected" : ""}>${escapePackageHtml(right.label)}</option>`).join("")}</select></label>`).join(""); const validation = `<button class="choice-check-btn" type="button" data-action="matching-validate" data-response-block-key="${escapePackageAttribute(blockKey)}">Conferir</button>`; const feedback = feedbackHtml(blockKey, options.responseState?.feedback); if (Array.isArray(options.dockExerciseParts)) { options.dockExerciseParts.push(validation + feedback); return `<section class="runtime-block package-matching-response">${renderPackageProse(data.prompt)}<div>${rows}</div></section>`; } return `<section class="runtime-block package-matching-response">${renderPackageProse(data.prompt)}<div>${rows}</div>${validation}${feedback}</section>`; },
  accessibleText(data) { return `${data.prompt} Origens: ${data.leftItems.map(({ label }) => label).join(", ")}. Destinos: ${data.rightItems.map(({ label }) => label).join(", ")}.`; },
  editableTargets(data) { return [{ path: "prompt", label: "Editar pergunta" }, ...data.leftItems.map((_, index) => ({ path: `leftItems[${index}].label`, label: `Editar origem ${index + 1}` })), ...data.rightItems.map((_, index) => ({ path: `rightItems[${index}].label`, label: `Editar destino ${index + 1}` }))]; },
  evaluate(data, answer) { const matches = answer?.matches && typeof answer.matches === "object" ? answer.matches : {}; const expected = Object.fromEntries(data.answerPairs.map(({ leftId, rightId }) => [leftId, rightId])); const results = data.leftItems.map(({ id }) => ({ leftId: id, received: String(matches[id] || ""), expected: expected[id], correct: String(matches[id] || "") === expected[id] })); return { correct: results.every(({ correct }) => correct), results }; }
});
