import { renderPackageInline, renderPackageProse } from "../../sdk/html.js";

function speciesText(species) { return `${species.coefficient ?? ""}${species.formula}${species.state ? `(${species.state})` : ""}`; }
function reactionAccessibleText(data) { const side = (items) => items.map((item) => `${item.coefficient || 1} ${item.name}, ${item.formula}${item.state ? `, estado ${item.state}` : ""}`).join(" mais "); return `${side(data.reactants)} produz ou se relaciona com ${side(data.products)}.`; }

export const reactionPackage = Object.freeze({
  manifest: Object.freeze({ id: "aralearn.resource.reaction", version: "1.0.0", label: "Reação", purpose: "Representar reagentes, produtos, proporções, estados e condições de uma reação.", slots: Object.freeze(["content", "feedback"]), cognitiveOperations: Object.freeze(["balance-reaction", "identify-reactant", "trace-transformation"]), responseCompatibility: Object.freeze(["aralearn.response.gap", "aralearn.response.choice"]), limitations: Object.freeze(["Não substitui a explicação microscópica ou energética da reação." ]), accessibility: "A equação possui descrição textual com nomes, coeficientes e estados." }),
  authoringContract: Object.freeze({ intent: "Declare espécies semanticamente, sem desenhar a equação.", required: Object.freeze(["reactionType", "reactants", "products"]), optional: Object.freeze(["prompt", "conditions"]), rules: Object.freeze(["Fórmula e nome são obrigatórios.", "Coeficiente omitido equivale visualmente a um."]), example: Object.freeze({ prompt: "Observe a formação de água.", reactionType: "forward", reactants: [{ id: "h", formula: "H₂", name: "hidrogênio", coefficient: 2, state: "g" }, { id: "o", formula: "O₂", name: "oxigênio", state: "g" }], products: [{ id: "w", formula: "H₂O", name: "água", coefficient: 2, state: "l" }], conditions: [] }) }),
  schema: Object.freeze({ type: "object", additionalProperties: false, required: ["reactionType", "reactants", "products"], properties: { prompt: { type: "string" }, reactionType: { type: "string", enum: ["forward", "reversible", "equilibrium"] }, reactants: { type: "array", minItems: 1, items: { type: "object", additionalProperties: false, required: ["id", "formula", "name"], properties: { id: { type: "string" }, formula: { type: "string" }, name: { type: "string" }, coefficient: { anyOf: [{ type: "integer", minimum: 1 }, { type: "string", minLength: 1 }] }, state: { type: "string", enum: ["s", "l", "g", "aq"] }, charge: { type: "integer" } } } }, products: { type: "array", minItems: 1, items: { type: "object", additionalProperties: false, required: ["id", "formula", "name"], properties: { id: { type: "string" }, formula: { type: "string" }, name: { type: "string" }, coefficient: { anyOf: [{ type: "integer", minimum: 1 }, { type: "string", minLength: 1 }] }, state: { type: "string", enum: ["s", "l", "g", "aq"] }, charge: { type: "integer" } } } }, conditions: { type: "array", items: { type: "string" } } } }),
  normalize(data) { const normalizeSpecies = (items) => (items || []).map((item) => ({ id: String(item?.id || "").trim(), formula: String(item?.formula || "").trim(), name: String(item?.name || "").trim(), ...(item?.coefficient != null ? { coefficient: item.coefficient } : {}), ...(item?.state ? { state: String(item.state) } : {}), ...(Number.isInteger(item?.charge) ? { charge: item.charge } : {}) })); return { ...(data?.prompt ? { prompt: String(data.prompt).trim() } : {}), reactionType: String(data?.reactionType || "forward"), reactants: normalizeSpecies(data?.reactants), products: normalizeSpecies(data?.products), ...(data?.conditions ? { conditions: data.conditions.map(String) } : {}) }; },
  validate(data) { const ids = [...data.reactants, ...data.products].map(({ id }) => id); return new Set(ids).size === ids.length ? [] : ["Espécies precisam de ids únicos."]; },
  render(data) { const arrow = data.reactionType === "forward" ? "→" : data.reactionType === "reversible" ? "⇄" : "⇌"; return `<div class="runtime-block runtime-reaction-block">${data.prompt ? renderPackageProse(data.prompt) : ""}<div class="package-reaction-equation" role="img" aria-label="${renderPackageInline(reactionAccessibleText(data))}">${data.reactants.map((item) => `<span title="${renderPackageInline(item.name)}">${renderPackageInline(speciesText(item))}</span>`).join(" + ")} <strong>${arrow}</strong> ${data.products.map((item) => `<span title="${renderPackageInline(item.name)}">${renderPackageInline(speciesText(item))}</span>`).join(" + ")}</div>${data.conditions?.length ? `<p>${data.conditions.map(renderPackageInline).join("; ")}</p>` : ""}</div>`; },
  accessibleText(data) { return reactionAccessibleText(data); },
  editableTargets(data) { return [...data.reactants.map((_, index) => ({ path: `reactants[${index}].name`, label: `Editar reagente ${index + 1}` })), ...data.products.map((_, index) => ({ path: `products[${index}].name`, label: `Editar produto ${index + 1}` }))]; }
});
