import { academicProfile } from "../../sdk/academic.js";
import { escapePackageAttribute, renderPackageInline, renderPackageProse } from "../../sdk/html.js";

export const packetLayoutPackage = Object.freeze({
  manifest: Object.freeze({ id: "aralearn.resource.packet_layout", version: "1.0.0", label: "Layout de pacote", purpose: "Representar campos contíguos de cabeçalhos, quadros e registros binários por posição e largura.", slots: Object.freeze(["content", "feedback"]), cognitiveOperations: Object.freeze(["locate-field", "calculate-offset", "interpret-header", "compare-width"]), academic: academicProfile({ domains: ["redes de computadores", "organização de computadores", "sistemas embarcados"], knowledgeObjects: ["cabeçalho de protocolo", "campo de bits", "offset"], conventions: ["ordem de transmissão explícita", "largura em bits", "offset inicial", "campos contíguos"], appropriateWhen: ["posição e largura dos campos alteram a interpretação"], avoidWhen: ["é preciso comparar registros heterogêneos", "o conteúdo não possui layout binário"], technologies: ["CSS grid proporcional", "HTML semântico"], practiceModes: ["exposition", "gap", "typing", "selection", "ordering"] }), responseCompatibility: Object.freeze(["aralearn.response.gap", "aralearn.response.choice"]), limitations: Object.freeze(["Divida cabeçalhos extensos por palavras de protocolo.", "Não comprima rótulos até ficarem ilegíveis."]), accessibility: "Cada campo é listado com nome, offset, largura e descrição." }),
  authoringContract: Object.freeze({ intent: "Declare campos na ordem de transmissão com largura em bits; o package calcula offsets e proporções.", required: Object.freeze(["unitBits", "fields"]), optional: Object.freeze(["prompt", "caption"]), rules: Object.freeze(["widthBits é inteiro positivo.", "Campos seguem a ordem do protocolo.", "Agrupe visualmente somente campos contíguos da mesma palavra."]), example: Object.freeze({ prompt: "Leia os campos iniciais do cabeçalho TCP.", unitBits: 32, fields: [{ id: "source", label: "Porta de origem", widthBits: 16, description: "Identifica o processo emissor." }, { id: "destination", label: "Porta de destino", widthBits: 16, description: "Identifica o processo receptor." }] }) }),
  schema: Object.freeze({ type: "object", additionalProperties: false, required: ["unitBits", "fields"], properties: { prompt: { type: "string" }, caption: { type: "string" }, unitBits: { type: "integer", minimum: 8, maximum: 64 }, fields: { type: "array", minItems: 1, maxItems: 24, items: { type: "object", additionalProperties: false, required: ["id", "label", "widthBits", "description"], properties: { id: { type: "string", minLength: 1 }, label: { type: "string", minLength: 1 }, widthBits: { type: "integer", minimum: 1, maximum: 256 }, description: { type: "string", minLength: 1 } } } } } }),
  normalize(data) { return { ...(data?.prompt ? { prompt: String(data.prompt).trim() } : {}), ...(data?.caption ? { caption: String(data.caption).trim() } : {}), unitBits: Number(data?.unitBits), fields: (data?.fields || []).map((field) => ({ id: String(field?.id || "").trim(), label: String(field?.label || "").trim(), widthBits: Number(field?.widthBits), description: String(field?.description || "").trim() })) }; },
  validate(data) { const ids = data.fields.map(({ id }) => id); return new Set(ids).size === ids.length ? [] : ["Campos precisam de ids únicos."]; },
  render(data) { let offset = 0; const fields = data.fields.map((field) => { const start = offset; offset += field.widthBits; return { ...field, start }; }); return `<div class="runtime-block package-packet-layout">${data.prompt ? renderPackageProse(data.prompt) : ""}<figure>${data.caption ? `<figcaption>${renderPackageInline(data.caption)}</figcaption>` : ""}<div class="package-packet-words" style="--packet-unit-bits:${data.unitBits}">${fields.map((field) => `<div class="package-packet-field" data-field-id="${escapePackageAttribute(field.id)}" style="--field-span:${Math.max(1, Math.min(data.unitBits, field.widthBits))}"><span class="package-packet-offset">${field.start}</span><strong>${renderPackageInline(field.label)}</strong><small>${field.widthBits} bit${field.widthBits === 1 ? "" : "s"}</small></div>`).join("")}</div><ol class="package-packet-legend">${fields.map((field) => `<li><strong>${renderPackageInline(field.label)}</strong><span>bits ${field.start}–${field.start + field.widthBits - 1}</span><small>${renderPackageInline(field.description)}</small></li>`).join("")}</ol></figure></div>`; },
  accessibleText(data) { let offset = 0; return `${data.prompt || "Layout de pacote."} ${data.fields.map((field) => { const start = offset; offset += field.widthBits; return `${field.label}, bits ${start} a ${offset - 1}: ${field.description}`; }).join("; ")}.`; },
  editableTargets(data) { return [...(data.prompt ? [{ path: "prompt", label: "Editar orientação" }] : []), ...(data.caption ? [{ path: "caption", label: "Editar legenda" }] : []), ...data.fields.flatMap((_, index) => [{ path: `fields[${index}].label`, label: `Editar campo ${index + 1}` }, { path: `fields[${index}].description`, label: `Editar descrição ${index + 1}` }])]; },
  practiceTargets(data) { return data.fields.flatMap((_, index) => [{ path: `fields[${index}].label`, label: `Lacuna no campo ${index + 1}`, modes: ["gap", "typing"] }, { path: `fields[${index}].description`, label: `Lacuna na descrição ${index + 1}`, modes: ["gap", "typing"] }]); }
});
