import { academicProfile } from "../../sdk/academic.js";
import { escapePackageAttribute, renderPackageInline, renderPackageProse } from "../../sdk/html.js";

const DEVICE_LABELS = Object.freeze({ host: "Host", router: "Roteador", switch: "Switch", firewall: "Firewall", access_point: "Ponto de acesso", server: "Servidor", cloud: "Rede externa", subnet: "Sub-rede" });

export const networkTopologyPackage = Object.freeze({
  manifest: Object.freeze({ id: "aralearn.resource.network_topology", version: "1.0.0", label: "Topologia de rede", purpose: "Representar equipamentos, segmentos e enlaces de uma rede segundo convenções de redes de computadores.", slots: Object.freeze(["content", "feedback"]), cognitiveOperations: Object.freeze(["trace-packet-path", "locate-network-role", "inspect-segmentation", "compare-link"]), academic: academicProfile({ domains: ["redes de computadores", "segurança de redes", "infraestrutura"], knowledgeObjects: ["equipamento de rede", "segmento", "enlace", "caminho de pacote"], conventions: ["papel do equipamento visível", "segmentos nomeados", "enlace com meio e direção quando relevantes", "endereçamento textual"], appropriateWhen: ["o papel físico ou lógico dos equipamentos e enlaces importa"], avoidWhen: ["a tarefa é teoria abstrata de grafos", "é preciso representar camadas internas de software"], technologies: ["HTML semântico", "lista de enlaces sem sobreposição"], practiceModes: ["exposition", "gap", "typing", "selection", "classification"] }), responseCompatibility: Object.freeze(["aralearn.response.gap", "aralearn.response.choice"]), limitations: Object.freeze(["Topologias densas devem ser divididas por segmento ou caminho.", "Não use ícones sem rótulo textual."]), accessibility: "Equipamentos são agrupados por segmento e os enlaces aparecem em lista textual completa." }),
  authoringContract: Object.freeze({ intent: "Declare segmentos, equipamentos e enlaces; não use graph genérico para papéis de rede.", required: Object.freeze(["segments", "devices", "links"]), optional: Object.freeze(["prompt"]), rules: Object.freeze(["Cada equipamento pertence a um segmento ou é externo.", "Meio, protocolo ou endereço só entram quando são didaticamente relevantes.", "Toda referência existe."]), example: Object.freeze({ prompt: "Acompanhe o caminho até o servidor.", segments: [{ id: "lan", label: "LAN 192.0.2.0/24" }], devices: [{ id: "client", label: "Cliente", kind: "host", segmentId: "lan", address: "192.0.2.10" }, { id: "switch", label: "Switch de acesso", kind: "switch", segmentId: "lan" }, { id: "server", label: "Servidor", kind: "server", segmentId: "lan", address: "192.0.2.20" }], links: [{ id: "l1", from: "client", to: "switch", medium: "Ethernet", directed: false }, { id: "l2", from: "switch", to: "server", medium: "Ethernet", directed: false }] }) }),
  schema: Object.freeze({ type: "object", additionalProperties: false, required: ["segments", "devices", "links"], properties: { prompt: { type: "string" }, segments: { type: "array", maxItems: 10, items: { type: "object", additionalProperties: false, required: ["id", "label"], properties: { id: { type: "string", minLength: 1 }, label: { type: "string", minLength: 1 } } } }, devices: { type: "array", minItems: 1, maxItems: 24, items: { type: "object", additionalProperties: false, required: ["id", "label", "kind", "segmentId"], properties: { id: { type: "string", minLength: 1 }, label: { type: "string", minLength: 1 }, kind: { type: "string", enum: Object.keys(DEVICE_LABELS) }, segmentId: { anyOf: [{ type: "string" }, { type: "null" }] }, address: { type: "string" } } } }, links: { type: "array", maxItems: 40, items: { type: "object", additionalProperties: false, required: ["id", "from", "to", "medium", "directed"], properties: { id: { type: "string", minLength: 1 }, from: { type: "string", minLength: 1 }, to: { type: "string", minLength: 1 }, medium: { type: "string", minLength: 1 }, protocol: { type: "string" }, directed: { type: "boolean" } } } } } }),
  normalize(data) { return { ...(data?.prompt ? { prompt: String(data.prompt).trim() } : {}), segments: (data?.segments || []).map((segment) => ({ id: String(segment?.id || "").trim(), label: String(segment?.label || "").trim() })), devices: (data?.devices || []).map((device) => ({ id: String(device?.id || "").trim(), label: String(device?.label || "").trim(), kind: String(device?.kind || "host"), segmentId: device?.segmentId == null ? null : String(device.segmentId), ...(device?.address ? { address: String(device.address).trim() } : {}) })), links: (data?.links || []).map((link) => ({ id: String(link?.id || "").trim(), from: String(link?.from || "").trim(), to: String(link?.to || "").trim(), medium: String(link?.medium || "").trim(), ...(link?.protocol ? { protocol: String(link.protocol).trim() } : {}), directed: link?.directed === true })) }; },
  validate(data) { const segments = new Set(data.segments.map(({ id }) => id)); const devices = new Set(data.devices.map(({ id }) => id)); const errors = []; if (segments.size !== data.segments.length || devices.size !== data.devices.length) errors.push("Segmentos e equipamentos precisam de ids únicos."); if (data.devices.some(({ segmentId }) => segmentId && !segments.has(segmentId))) errors.push("Equipamento referencia segmento inexistente."); if (data.links.some(({ from, to }) => !devices.has(from) || !devices.has(to))) errors.push("Enlace referencia equipamento inexistente."); return errors; },
  render(data) { const names = new Map(data.devices.map(({ id, label }) => [id, label])); const sections = [...data.segments.map((segment) => ({ ...segment, devices: data.devices.filter(({ segmentId }) => segmentId === segment.id) })), { id: "external", label: "Fora dos segmentos", devices: data.devices.filter(({ segmentId }) => segmentId === null) }].filter(({ devices }) => devices.length); return `<div class="runtime-block package-network-topology">${data.prompt ? renderPackageProse(data.prompt) : ""}<div class="package-network-segments">${sections.map((segment) => `<section><h4>${renderPackageInline(segment.label)}</h4><div>${segment.devices.map((device) => `<article data-device-id="${escapePackageAttribute(device.id)}"><span>${DEVICE_LABELS[device.kind]}</span><strong>${renderPackageInline(device.label)}</strong>${device.address ? `<code>${renderPackageInline(device.address)}</code>` : ""}</article>`).join("")}</div></section>`).join("")}</div><ol class="package-network-links">${data.links.map((link) => `<li><strong>${renderPackageInline(names.get(link.from))}</strong><span>${link.directed ? "→" : "↔"}</span><strong>${renderPackageInline(names.get(link.to))}</strong><small>${renderPackageInline(link.medium)}${link.protocol ? ` · ${renderPackageInline(link.protocol)}` : ""}</small></li>`).join("")}</ol></div>`; },
  accessibleText(data) { const names = new Map(data.devices.map(({ id, label }) => [id, label])); return `${data.prompt || "Topologia de rede."} ${data.devices.map((device) => `${device.label}, ${DEVICE_LABELS[device.kind]}${device.address ? `, endereço ${device.address}` : ""}`).join("; ")}. Enlaces: ${data.links.map((link) => `${names.get(link.from)} ${link.directed ? "para" : "com"} ${names.get(link.to)}, ${link.medium}${link.protocol ? `, ${link.protocol}` : ""}`).join("; ")}.`; },
  editableTargets(data) { return [...(data.prompt ? [{ path: "prompt", label: "Editar orientação" }] : []), ...data.segments.map((_, index) => ({ path: `segments[${index}].label`, label: `Editar segmento ${index + 1}` })), ...data.devices.flatMap((device, index) => [{ path: `devices[${index}].label`, label: `Editar equipamento ${index + 1}` }, ...(device.address ? [{ path: `devices[${index}].address`, label: `Editar endereço ${index + 1}` }] : [])]), ...data.links.flatMap((link, index) => [{ path: `links[${index}].medium`, label: `Editar meio ${index + 1}` }, ...(link.protocol ? [{ path: `links[${index}].protocol`, label: `Editar protocolo ${index + 1}` }] : [])])]; },
  practiceTargets(data) { return [...data.devices.map((_, index) => ({ path: `devices[${index}].label`, label: `Lacuna no equipamento ${index + 1}`, modes: ["gap", "typing"] })), ...data.links.flatMap((link, index) => link.protocol ? [{ path: `links[${index}].protocol`, label: `Lacuna no protocolo ${index + 1}`, modes: ["gap", "typing"] }] : [])]; }
});
