import { academicProfile } from "../../sdk/academic.js";
import { renderPackageInline, renderPackageProse } from "../../sdk/html.js";

export const algorithmTracePackage = Object.freeze({
  manifest: Object.freeze({ id: "aralearn.resource.algorithm_trace", version: "1.0.0", label: "Rastreamento de algoritmo", purpose: "Acompanhar passo a passo o estado de variáveis, condição e saída durante a execução de um algoritmo.", slots: Object.freeze(["content", "feedback"]), cognitiveOperations: Object.freeze(["trace-execution", "predict-state", "locate-bug", "explain-iteration"]), academic: academicProfile({ domains: ["lógica de programação", "algoritmos", "estruturas de dados"], knowledgeObjects: ["estado de execução", "variável", "iteração", "saída"], conventions: ["um passo por linha", "variáveis em colunas estáveis", "mudança de estado identificável"], appropriateWhen: ["o estudante precisa simular a execução e observar mudança de estado"], avoidWhen: ["a sintaxe do código é o objeto principal", "há somente uma sequência verbal"], technologies: ["tabela HTML semântica"], practiceModes: ["exposition", "gap", "typing", "selection", "ordering"] }), responseCompatibility: Object.freeze(["aralearn.response.gap", "aralearn.response.choice"]), limitations: Object.freeze(["Mostre somente variáveis relevantes ao objetivo.", "Divida rastreamentos longos em trechos."]), accessibility: "Cada passo é uma linha com ação, valores das variáveis e saída." }),
  authoringContract: Object.freeze({ intent: "Declare as variáveis observadas e os estados sucessivos; não use table genérica para simulação de código.", required: Object.freeze(["variables", "steps"]), optional: Object.freeze(["prompt"]), rules: Object.freeze(["Cada step contém um valor textual por variável.", "A ação descreve a instrução executada, não apenas o número da linha."]), example: Object.freeze({ prompt: "Acompanhe o contador.", variables: ["i", "soma"], steps: [{ id: "s0", action: "Inicializar", values: ["0", "0"], output: "" }, { id: "s1", action: "Somar i e incrementar", values: ["1", "0"], output: "" }] }) }),
  schema: Object.freeze({ type: "object", additionalProperties: false, required: ["variables", "steps"], properties: { prompt: { type: "string" }, variables: { type: "array", minItems: 1, maxItems: 8, uniqueItems: true, items: { type: "string", minLength: 1 } }, steps: { type: "array", minItems: 1, maxItems: 30, items: { type: "object", additionalProperties: false, required: ["id", "action", "values"], properties: { id: { type: "string", minLength: 1 }, action: { type: "string", minLength: 1 }, values: { type: "array", minItems: 1, maxItems: 8, items: { type: "string" } }, condition: { type: "string" }, output: { type: "string" } } } } } }),
  normalize(data) { return { ...(data?.prompt ? { prompt: String(data.prompt).trim() } : {}), variables: (data?.variables || []).map(String), steps: (data?.steps || []).map((step) => ({ id: String(step?.id || "").trim(), action: String(step?.action || "").trim(), values: (step?.values || []).map(String), ...(step?.condition ? { condition: String(step.condition).trim() } : {}), ...(step?.output !== undefined ? { output: String(step.output) } : {}) })) }; },
  validate(data) { const errors = []; if (new Set(data.steps.map(({ id }) => id)).size !== data.steps.length) errors.push("Passos precisam de ids únicos."); data.steps.forEach((step, index) => { if (step.values.length !== data.variables.length) errors.push(`Passo ${index + 1} não informa todas as variáveis.`); }); return errors; },
  render(data) { return `<div class="runtime-block package-algorithm-trace">${data.prompt ? renderPackageProse(data.prompt) : ""}<div class="runtime-table-wrap"><div class="runtime-table-frame"><table class="runtime-table"><thead><tr><th scope="col">Passo e ação</th>${data.variables.map((variable) => `<th scope="col"><code>${renderPackageInline(variable)}</code></th>`).join("")}<th scope="col">Saída</th></tr></thead><tbody>${data.steps.map((step, index) => `<tr><th scope="row"><span>${index + 1}</span><strong>${renderPackageInline(step.action)}</strong>${step.condition ? `<small>${renderPackageInline(step.condition)}</small>` : ""}</th>${step.values.map((value) => `<td><code>${renderPackageInline(value)}</code></td>`).join("")}<td>${renderPackageInline(step.output || "—")}</td></tr>`).join("")}</tbody></table></div></div></div>`; },
  accessibleText(data) { return `${data.prompt || "Rastreamento."} ${data.steps.map((step, index) => `Passo ${index + 1}, ${step.action}: ${data.variables.map((variable, variableIndex) => `${variable} vale ${step.values[variableIndex]}`).join(", ")}${step.output ? `; saída ${step.output}` : ""}`).join(". ")}.`; },
  editableTargets(data) { return [...(data.prompt ? [{ path: "prompt", label: "Editar orientação" }] : []), ...data.variables.map((_, index) => ({ path: `variables[${index}]`, label: `Editar variável ${index + 1}` })), ...data.steps.flatMap((step, index) => [{ path: `steps[${index}].action`, label: `Editar ação ${index + 1}` }, ...step.values.map((_, valueIndex) => ({ path: `steps[${index}].values[${valueIndex}]`, label: `Editar valor ${index + 1}.${valueIndex + 1}` })), ...(step.condition ? [{ path: `steps[${index}].condition`, label: `Editar condição ${index + 1}` }] : []), ...(step.output !== undefined ? [{ path: `steps[${index}].output`, label: `Editar saída ${index + 1}` }] : [])])]; }
});
