import { readFile, mkdir, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const upstreamDirectory = "src/bibliography/upstream";

function verifyHash(bytes, expected, name) {
  if (createHash("sha256").update(bytes).digest("hex") !== expected) {
    throw new Error(`Fonte bibliográfica divergente do hash aprovado: ${name}.`);
  }
}

// CC-BY-SA-3.0 adaptation of the pinned UFRGS style; upstream XML remains intact.
export function applyAbntElectronicLocationPatch(source) {
  const original = '          <text variable="collection-title"/>\n          <text macro="pages"/>';
  if (source.split(original).length !== 2) throw new Error("O ponto do ajuste de localização eletrônica ABNT mudou.");
  return source.replace(original, [
    '          <text variable="collection-title"/>',
    '          <!-- AraLearn, 2026-09-05, abnt-elocation-v1: an article number is not a page range. -->',
    '          <choose>',
    '            <if variable="page"><text macro="pages"/></if>',
    '            <else-if variable="number"><text variable="number"/></else-if>',
    '          </choose>'
  ].join("\n"));
}

export function applyAbntAccessPunctuationPatch(source) {
  // The access macro already punctuates URL and accessed date. The webpage and
  // report branches add a second period after its trailing space when no date exists.
  for (const suffix of [". ", "."]) {
    const original = `            <text macro="access" suffix="${suffix}"/>`;
    if (source.split(original).length !== 2) throw new Error("O ponto do ajuste de pontuação de acesso ABNT mudou.");
    source = source.replace(original,
      '            <!-- AraLearn, 2026-09-05, abnt-access-punctuation-v1: access already supplies its punctuation. -->\n' +
      '            <text macro="access"/>');
  }
  return source;
}

export function applyAbntEmptyMetadataSeparatorPatch(source) {
  const replacements = [
    ['            <text macro="publisher" prefix=". "/>', [
      '            <!-- AraLearn, 2026-09-05, abnt-empty-separator-v1: the title already closes when intermediate metadata is absent. -->',
      '            <choose>',
      '              <if variable="editor translator container-author container-title collection-title" match="any">',
      '                <text macro="publisher" prefix=". "/>',
      '              </if>',
      '              <else><text macro="publisher"/></else>',
      '            </choose>'
    ].join("\n")],
    ['          <text macro="issued" prefix=", "/>', [
      '          <!-- AraLearn, 2026-09-05, abnt-empty-separator-v1: publisher supplies its comma; absent publication metadata supplies none. -->',
      '          <choose>',
      '            <if variable="publisher"><text macro="issued"/></if>',
      '            <else-if variable="publisher-place"><text macro="issued" prefix=", "/></else-if>',
      '            <else><text macro="issued"/></else>',
      '          </choose>'
    ].join("\n")]
  ];
  for (const [original, replacement] of replacements) {
    if (source.split(original).length !== 2) throw new Error("O ponto do ajuste de separadores de metadados ABNT mudou.");
    source = source.replace(original, replacement);
  }
  return source;
}

export function buildBibliographyModule(source, expectedHash) {
  const bytes = Buffer.isBuffer(source) ? source : Buffer.from(source, "utf8");
  verifyHash(bytes, expectedHash, "citeproc");
  const sourceText = bytes.toString("utf8");
  const debug = [
    '    debug: function(str) { // default debug function',
    '        if ("undefined" === typeof console) {',
    '            dump("CSL: " + str + "\\n");',
    '        } else {',
    '            console.log("citeproc-js warning: " + str);',
    '        }',
    '    },'
  ].join("\n");
  if (sourceText.split(debug).length !== 2) throw new Error("O emissor de diagnóstico bibliográfico mudou.");
  const adapted = sourceText.replace(debug, [
    '    // AraLearn, 2026-09-05: reference data must not enter operational logs.',
    '    debug: function() {},'
  ].join("\n"));
  return "/* citeproc 2.4.63 | CPAL-1.0 | Generated by scripts/buildBibliographyVendor.mjs.\n" +
    " * Original source: src/bibliography/upstream/citeproc-2.4.63.cjs.\n" +
    " * Modification: CommonJS/ESM wrapper and suppressed debug output; upstream file is unchanged.\n" +
    " * Notices and license: public/vendor/bibliography/NOTICE.txt and CPAL-1.0.txt.\n" +
    " */\nconst module = { exports: {} };\n" + adapted +
    "\nexport default module.exports;\n";
}

export async function bibliographyVendorOutputs(root = repositoryRoot) {
  const upstream = path.join(root, upstreamDirectory);
  const manifest = JSON.parse(await readFile(path.join(upstream, "manifest.json"), "utf8"));
  if (manifest.schemaVersion !== 1 || manifest.engine.version !== "2.4.63") {
    throw new Error("Manifesto de bibliografia não reconhecido.");
  }
  const source = await readFile(path.join(upstream, manifest.engine.file));
  const assets = { styles: {}, locales: {} };
  for (const asset of manifest.assets) {
    const bytes = await readFile(path.join(upstream, asset.file));
    verifyHash(bytes, asset.sha256, asset.file);
    const source = bytes.toString("utf8");
    assets[asset.kind === "style" ? "styles" : "locales"][asset.key] = asset.key === "abnt-2025"
      ? applyAbntEmptyMetadataSeparatorPatch(applyAbntAccessPunctuationPatch(applyAbntElectronicLocationPatch(source))) : source;
  }
  for (const notice of manifest.notices) {
    verifyHash(await readFile(path.resolve(root, notice.file)), notice.sha256, notice.file);
  }
  const styleModule = "/* CSL styles/locales | CC-BY-SA-3.0 | Generated by scripts/buildBibliographyVendor.mjs.\n" +
    " * Original metadata, attribution and license notices are preserved inside each XML source.\n" +
    " * Sources and hashes: src/bibliography/upstream/manifest.json.\n */\n" +
    `export const styles = Object.freeze(${JSON.stringify(assets.styles)});\n` +
    `export const locales = Object.freeze(${JSON.stringify(assets.locales)});\n`;
  return new Map([
    ["src/bibliography/vendor/citeproc.generated.js", buildBibliographyModule(source, manifest.engine.sha256)],
    ["src/bibliography/vendor/styles.generated.js", styleModule]
  ]);
}

async function main() {
  const args = process.argv.slice(2);
  if (args.some((value) => value !== "--check")) throw new Error("Use somente --check ou nenhum argumento.");
  const check = args.includes("--check");
  const divergent = [];
  for (const [relative, expected] of await bibliographyVendorOutputs()) {
    const target = path.join(repositoryRoot, relative);
    const current = await readFile(target, "utf8").catch(() => null);
    if (current === expected) continue;
    divergent.push(relative);
    if (!check) {
      await mkdir(path.dirname(target), { recursive: true });
      await writeFile(target, expected, "utf8");
    }
  }
  if (check && divergent.length) throw new Error(`Vendor bibliográfico divergente: ${divergent.join(", ")}.`);
  console.log(check ? "Vendor bibliográfico confere com os fontes fixados." : "Vendor bibliográfico atualizado.");
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) await main();
