import { escapePackageAttribute, renderPackageInline, renderPackageProse } from "../../sdk/html.js";

function normalizeAnswer(value) { return String(value ?? "").normalize("NFC").trim(); }

export const gapResponsePackage = Object.freeze({
  manifest: Object.freeze({
    id: "aralearn.response.gap", version: "1.0.0", label: "Lacuna",
    purpose: "Pedir recuperação ou discriminação exatamente no campo semântico declarado pelo conteúdo.", slots: Object.freeze(["response"]),
    cognitiveOperations: Object.freeze(["recall", "complete", "label", "calculate"]), responseCompatibility: Object.freeze([]),
    limitations: Object.freeze(["O package de conteúdo precisa declarar o targetPath como editável por resposta." ]), accessibility: "Cada lacuna tem prompt, rótulo e controle nativo próprios."
  }),
  authoringContract: Object.freeze({ intent: "Declare lacunas com targetInstanceId e targetPath inequívocos, resposta formal e modo.", required: Object.freeze(["blanks"]), optional: Object.freeze(["prompt"]), rules: Object.freeze(["Não codifique lacunas dentro de strings.", "AcceptedAnswers só contém equivalentes formalmente aceitos."]), example: Object.freeze({ prompt: "Complete o termo.", blanks: [{ id: "protocol", targetInstanceId: "body-1", targetPath: "text:protocol", responseMode: "text", answer: "protocolo" }] }) }),
  schema: Object.freeze({ type: "object", additionalProperties: false, required: ["blanks"], properties: { prompt: { type: "string", maxLength: 2000 }, blanks: { type: "array", minItems: 1, maxItems: 12, items: { type: "object", additionalProperties: false, required: ["id", "targetInstanceId", "targetPath", "responseMode", "answer"], properties: { id: { type: "string", minLength: 1 }, targetInstanceId: { type: "string", minLength: 1 }, targetPath: { type: "string", minLength: 1 }, label: { type: "string" }, responseMode: { type: "string", enum: ["text", "choice"] }, answer: { type: "string", minLength: 1 }, acceptedAnswers: { type: "array", uniqueItems: true, items: { type: "string", minLength: 1 } }, distractors: { type: "array", uniqueItems: true, items: { type: "string", minLength: 1 } } } } } } }),
  normalize(data) { return { ...(data?.prompt ? { prompt: String(data.prompt).trim() } : {}), blanks: (data?.blanks || []).map((blank) => ({ id: String(blank?.id || "").trim(), targetInstanceId: String(blank?.targetInstanceId || "").trim(), targetPath: String(blank?.targetPath || "").trim(), ...(blank?.label ? { label: String(blank.label).trim() } : {}), responseMode: String(blank?.responseMode || "text").trim(), answer: normalizeAnswer(blank?.answer), ...(blank?.acceptedAnswers ? { acceptedAnswers: blank.acceptedAnswers.map(normalizeAnswer) } : {}), ...(blank?.distractors ? { distractors: blank.distractors.map(normalizeAnswer) } : {}) })) }; },
  validate(data) { const errors = []; if (new Set(data.blanks.map(({ id }) => id)).size !== data.blanks.length) errors.push("Lacunas precisam de ids únicos."); data.blanks.forEach((blank) => { if (blank.responseMode === "choice" && (!blank.distractors || blank.distractors.length < 1)) errors.push(`Lacuna ${blank.id} por escolha precisa de distrator.`); if (blank.distractors?.includes(blank.answer)) errors.push(`Lacuna ${blank.id} repete a resposta nos distratores.`); }); return errors; },
  render(data) { return `<div class="package-gap-response">${data.prompt ? renderPackageProse(data.prompt) : ""}${data.blanks.map((blank) => blank.responseMode === "choice" ? `<label>${renderPackageInline(blank.label || "Complete")}<select data-gap-id="${escapePackageAttribute(blank.id)}"><option value=""></option>${[blank.answer, ...(blank.distractors || [])].map((value) => `<option value="${escapePackageAttribute(value)}">${renderPackageInline(value)}</option>`).join("")}</select></label>` : `<label>${renderPackageInline(blank.label || "Complete")}<input type="text" data-gap-id="${escapePackageAttribute(blank.id)}" autocomplete="off"></label>`).join("")}</div>`; },
  accessibleText(data) { return `${data.prompt || "Complete as lacunas."} ${data.blanks.map((blank) => blank.label || blank.id).join("; ")}`; },
  editableTargets() { return []; },
  evaluate(data, answer) { const values = answer?.values && typeof answer.values === "object" ? answer.values : {}; const results = data.blanks.map((blank) => { const received = normalizeAnswer(values[blank.id]); const accepted = [blank.answer, ...(blank.acceptedAnswers || [])].map(normalizeAnswer); return { id: blank.id, correct: accepted.includes(received), received, expected: blank.answer }; }); return { correct: results.every(({ correct }) => correct), results }; }
});
