import { escapePackageAttribute, renderPackageInline, renderPackageProse } from "../../sdk/html.js";

function numericPoints(data) { return data.series.flatMap((series) => series.values.map(([x, y]) => ({ series: series.name, x, y: Number(y) })).filter(({ y }) => Number.isFinite(y))); }
function chartAccessibleText(data) { return `${data.prompt || "Gráfico."} Eixo x: ${data.xAxis.label}. Eixo y: ${data.yAxis.label}${data.yAxis.unit ? ` em ${data.yAxis.unit}` : ""}. ${data.series.map((series) => `${series.name}: ${series.values.map(([x, y]) => `${x}, ${y}`).join("; ")}`).join(". ")}`; }

export const chartPackage = Object.freeze({
  manifest: Object.freeze({ id: "aralearn.resource.chart", version: "1.0.0", label: "Gráfico estatístico", purpose: "Tornar tendência, distribuição ou comparação quantitativa visualmente observável.", slots: Object.freeze(["content", "feedback"]), cognitiveOperations: Object.freeze(["compare-quantity", "identify-trend", "inspect-distribution", "find-outlier"]), responseCompatibility: Object.freeze(["aralearn.response.gap", "aralearn.response.choice"]), limitations: Object.freeze(["Eixos, unidade e escala precisam ser declarados.", "Não use para poucos valores melhor explicados em prosa." ]), accessibility: "Séries e valores são repetidos em descrição textual."
  }),
  authoringContract: Object.freeze({ intent: "Declare eixos e séries; o motor deriva escala e marcas.", required: Object.freeze(["chartType", "xAxis", "yAxis", "series"]), optional: Object.freeze(["prompt"]), rules: Object.freeze(["Unidades não ficam implícitas.", "Compare apenas séries semanticamente compatíveis."]), example: Object.freeze({ prompt: "Observe o crescimento.", chartType: "line", xAxis: { label: "Tempo" }, yAxis: { label: "Valor", unit: "ms" }, series: [{ id: "s1", name: "Latência", values: [["1", 10], ["2", 18], ["3", 25]] }] }) }),
  schema: Object.freeze({ type: "object", additionalProperties: false, required: ["chartType", "xAxis", "yAxis", "series"], properties: { prompt: { type: "string" }, chartType: { type: "string", enum: ["bar", "line", "scatter", "histogram", "boxplot"] }, xAxis: { type: "object", additionalProperties: false, required: ["label"], properties: { label: { type: "string" }, unit: { type: "string" } } }, yAxis: { type: "object", additionalProperties: false, required: ["label"], properties: { label: { type: "string" }, unit: { type: "string" } } }, series: { type: "array", minItems: 1, maxItems: 6, items: { type: "object", additionalProperties: false, required: ["id", "name", "values"], properties: { id: { type: "string" }, name: { type: "string" }, values: { type: "array", minItems: 1, items: { type: "array", minItems: 2, maxItems: 2, prefixItems: [{ anyOf: [{ type: "string" }, { type: "number" }] }, { type: "number" }] } } } } } } }),
  normalize(data) { return { ...(data?.prompt ? { prompt: String(data.prompt).trim() } : {}), chartType: String(data?.chartType || "line"), xAxis: structuredClone(data?.xAxis), yAxis: structuredClone(data?.yAxis), series: (data?.series || []).map((series) => ({ id: String(series?.id || "").trim(), name: String(series?.name || "").trim(), values: (series?.values || []).map(([x, y]) => [x, Number(y)]) })) }; },
  validate(data) { const ids = data.series.map(({ id }) => id); return new Set(ids).size === ids.length ? [] : ["Séries precisam de ids únicos."]; },
  render(data) { const points = numericPoints(data); const max = Math.max(1, ...points.map(({ y }) => y)); const categories = [...new Set(points.map(({ x }) => String(x)))]; return `<div class="runtime-block runtime-chart-block">${data.prompt ? renderPackageProse(data.prompt) : ""}<svg class="package-chart" viewBox="0 0 120 82" role="img" aria-label="${escapePackageAttribute(chartAccessibleText(data))}"><line x1="12" y1="68" x2="112" y2="68"/><line x1="12" y1="8" x2="12" y2="68"/>${points.map((point, index) => { const x = 18 + (categories.indexOf(String(point.x)) * (88 / Math.max(1, categories.length - 1))); const y = 68 - (point.y / max) * 54; return `<circle class="package-chart-point tone-${index % 6}" cx="${x}" cy="${y}" r="3"><title>${renderPackageInline(`${point.series}: ${point.x}, ${point.y}`)}</title></circle>`; }).join("")}</svg><p class="package-chart-axis">${renderPackageInline(data.xAxis.label)} · ${renderPackageInline(data.yAxis.label)}${data.yAxis.unit ? ` (${renderPackageInline(data.yAxis.unit)})` : ""}</p></div>`; },
  accessibleText(data) { return chartAccessibleText(data); }, editableTargets(data) { return data.series.map((_, index) => ({ path: `series[${index}].name`, label: `Editar série ${index + 1}` })); }
});
