import { escapePackageAttribute, renderPackageInline, renderPackageProse } from "../../sdk/html.js";
import { academicProfile } from "../../sdk/academic.js";

function renderSpecies(species) { const charge = species.charge ? `${Math.abs(species.charge)}${species.charge > 0 ? "+" : "−"}` : ""; const formula = `<mtext class="package-reaction-formula">${renderPackageInline(species.formula)}</mtext>`; const coefficient = species.coefficient != null ? `<mtext class="package-reaction-coefficient">${renderPackageInline(String(species.coefficient))}</mtext><mspace class="package-reaction-coefficient-space" width="0.35em"/>` : ""; return `<mrow class="package-reaction-species">${coefficient}${charge ? `<msup>${formula}<mtext>${renderPackageInline(charge)}</mtext></msup>` : formula}${species.state ? `<mtext class="package-reaction-state">(${renderPackageInline(species.state)})</mtext>` : ""}</mrow>`; }
function renderSide(items) { return items.map(renderSpecies).join('<mspace class="package-reaction-operator-space" width="0.6em"/><mo class="package-reaction-plus">+</mo><mspace class="package-reaction-operator-space" width="0.6em"/>'); }
function reactionAccessibleText(data) {
  const side = (items) => items.map((item) => `${item.coefficient || 1} ${item.name}, ${item.formula}${item.state ? `, estado ${item.state}` : ""}${item.charge ? `, carga ${item.charge}` : ""}`).join(" mais ");
  const transition = data.reactionType === "equilibrium" ? "está em equilíbrio com"
    : data.reactionType === "reversible" ? "transforma-se reversivelmente em" : "produz";
  return `${side(data.reactants)} ${transition} ${side(data.products)}.${data.conditions?.length ? ` Condições: ${data.conditions.join("; ")}.` : ""}`;
}

export const reactionPackage = Object.freeze({
  manifest: Object.freeze({ id: "aralearn.resource.reaction", version: "1.0.0", label: "Reação", purpose: "Representar reagentes, produtos, proporções, estados e condições de uma reação.", slots: Object.freeze(["content", "feedback"]), taskOperations: Object.freeze(["balance-reaction", "identify-reactant", "trace-transformation"]), academic: academicProfile({ domains: ["química"], knowledgeObjects: ["equação de reação", "espécie química", "coeficiente estequiométrico"], conventions: ["reagentes à esquerda", "produtos à direita", "estados e condições explícitos"], appropriateWhen: ["a transformação química simbólica é parte da tarefa"], avoidWhen: ["a tarefa exige somente descrição macroscópica"], technologies: ["HTML semântico", "notação química estruturada"], practiceModes: ["exposition", "gap", "typing", "selection"] }), responseCompatibility: Object.freeze(["aralearn.response.gap", "aralearn.response.choice"]), limitations: Object.freeze(["Não substitui a explicação microscópica ou energética da reação." ]), accessibility: "A equação possui descrição textual com nomes, coeficientes e estados." }),
  authoringContract: Object.freeze({ intent: "Declare espécies semanticamente, sem desenhar a equação.", required: Object.freeze(["reactionType", "reactants", "products"]), optional: Object.freeze(["prompt", "conditions"]), rules: Object.freeze(["Fórmula e nome são obrigatórios.", "Coeficiente omitido equivale visualmente a um."]), example: Object.freeze({ prompt: "Observe a formação de água.", reactionType: "forward", reactants: [{ id: "h", formula: "H₂", name: "hidrogênio", coefficient: 2, state: "g" }, { id: "o", formula: "O₂", name: "oxigênio", state: "g" }], products: [{ id: "w", formula: "H₂O", name: "água", coefficient: 2, state: "l" }], conditions: [] }) }),
  schema: Object.freeze({ type: "object", additionalProperties: false, required: ["reactionType", "reactants", "products"], properties: { prompt: { type: "string" }, reactionType: { type: "string", enum: ["forward", "reversible", "equilibrium"] }, reactants: { type: "array", minItems: 1, items: { type: "object", additionalProperties: false, required: ["id", "formula", "name"], properties: { id: { type: "string" }, formula: { type: "string" }, name: { type: "string" }, coefficient: { anyOf: [{ type: "integer", minimum: 1 }, { type: "string", minLength: 1 }] }, state: { type: "string", enum: ["s", "l", "g", "aq"] }, charge: { type: "integer" } } } }, products: { type: "array", minItems: 1, items: { type: "object", additionalProperties: false, required: ["id", "formula", "name"], properties: { id: { type: "string" }, formula: { type: "string" }, name: { type: "string" }, coefficient: { anyOf: [{ type: "integer", minimum: 1 }, { type: "string", minLength: 1 }] }, state: { type: "string", enum: ["s", "l", "g", "aq"] }, charge: { type: "integer" } } } }, conditions: { type: "array", items: { type: "string" } } } }),
  normalize(data) { const normalizeSpecies = (items) => (items || []).map((item) => ({ id: String(item?.id || "").trim(), formula: String(item?.formula || "").trim(), name: String(item?.name || "").trim(), ...(item?.coefficient != null ? { coefficient: String(item.coefficient).trim() } : {}), ...(item?.state ? { state: String(item.state) } : {}), ...(Number.isInteger(item?.charge) ? { charge: item.charge } : {}) })); return { ...(data?.prompt ? { prompt: String(data.prompt).trim() } : {}), reactionType: String(data?.reactionType || "forward"), reactants: normalizeSpecies(data?.reactants), products: normalizeSpecies(data?.products), ...(data?.conditions ? { conditions: data.conditions.map((item) => String(item).trim()) } : {}) }; },
  validate(data) { const ids = [...data.reactants, ...data.products].map(({ id }) => id); return new Set(ids).size === ids.length ? [] : ["Espécies precisam de ids únicos."]; },
  render(data) { const arrow = data.reactionType === "forward" ? "→" : data.reactionType === "reversible" ? "⇄" : "⇌"; const arrowMarkup = `<mo class="package-reaction-arrow">${arrow}</mo>`; const arrowWithCondition = data.conditions?.length ? `<mover>${arrowMarkup}<mtext class="package-reaction-arrow-condition">${data.conditions.map(renderPackageInline).join("; ")}</mtext></mover>` : arrowMarkup; const transition = `<mspace class="package-reaction-transition-space" width="0.8em"/>${arrowWithCondition}<mspace class="package-reaction-transition-space" width="0.8em"/>`; return `<div class="runtime-block runtime-reaction-block">${data.prompt ? renderPackageProse(data.prompt) : ""}<figure class="package-reaction"><math class="package-reaction-equation" display="block" aria-label="${escapePackageAttribute(reactionAccessibleText(data))}"><mrow><mrow class="package-reaction-side">${renderSide(data.reactants)}</mrow>${transition}<mrow class="package-reaction-side">${renderSide(data.products)}</mrow></mrow></math></figure></div>`; },
  accessibleText(data) { return reactionAccessibleText(data); },
  editableTargets(data) { const speciesTargets = (side, items) => items.flatMap((item, index) => [...(item.coefficient != null ? [{ path: `${side}[${index}].coefficient`, label: `Editar coeficiente ${index + 1}` }] : []), { path: `${side}[${index}].formula`, label: `Editar fórmula ${index + 1}` }, ...(item.state ? [{ path: `${side}[${index}].state`, label: `Editar estado físico ${index + 1}` }] : [])]); return [...(data.prompt ? [{ path: "prompt", label: "Editar orientação" }] : []), ...speciesTargets("reactants", data.reactants), ...speciesTargets("products", data.products), ...(data.conditions || []).map((_, index) => ({ path: `conditions[${index}]`, label: `Editar condição ${index + 1}` }))]; },
  practiceTargets(data) { const speciesTargets = (side, items) => items.flatMap((item, index) => [...(item.coefficient != null ? [{ path: `${side}[${index}].coefficient`, label: `Lacuna no coeficiente ${index + 1} de ${side === "reactants" ? "reagente" : "produto"}`, modes: ["gap", "typing"] }] : []), { path: `${side}[${index}].formula`, label: `Lacuna na fórmula ${index + 1} de ${side === "reactants" ? "reagente" : "produto"}`, modes: ["gap", "typing"] }, ...(item.state ? [{ path: `${side}[${index}].state`, label: `Lacuna no estado físico ${index + 1}`, modes: ["gap", "typing"] }] : [])]); return [...speciesTargets("reactants", data.reactants), ...speciesTargets("products", data.products), ...(data.conditions || []).map((_, index) => ({ path: `conditions[${index}]`, label: `Lacuna na condição ${index + 1}`, modes: ["gap", "typing"] }))]; }
});
