import { escapePackageAttribute, renderPackageInline, renderPackageProse } from "../../sdk/html.js";
import { academicProfile } from "../../sdk/academic.js";

function renderSpecies(species) { const charge = species.charge ? `${Math.abs(species.charge)}${species.charge > 0 ? "+" : "−"}` : ""; return `<span class="package-reaction-species" title="${escapePackageAttribute(species.name)}">${species.coefficient != null ? `<span class="package-reaction-coefficient">${renderPackageInline(String(species.coefficient))}</span>` : ""}<span class="package-reaction-formula">${renderPackageInline(species.formula)}</span>${charge ? `<sup>${renderPackageInline(charge)}</sup>` : ""}${species.state ? `<span class="package-reaction-state">(${renderPackageInline(species.state)})</span>` : ""}<span class="visually-hidden">, ${renderPackageInline(species.name)}</span></span>`; }
function renderSide(items) { return items.map(renderSpecies).join('<span class="package-reaction-plus" aria-hidden="true">+</span>'); }
function reactionAccessibleText(data) { const side = (items) => items.map((item) => `${item.coefficient || 1} ${item.name}, ${item.formula}${item.state ? `, estado ${item.state}` : ""}`).join(" mais "); return `${side(data.reactants)} produz ou se relaciona com ${side(data.products)}.`; }

export const reactionPackage = Object.freeze({
  manifest: Object.freeze({ id: "aralearn.resource.reaction", version: "1.0.0", label: "Reação", purpose: "Representar reagentes, produtos, proporções, estados e condições de uma reação.", slots: Object.freeze(["content", "feedback"]), cognitiveOperations: Object.freeze(["balance-reaction", "identify-reactant", "trace-transformation"]), academic: academicProfile({ domains: ["química"], knowledgeObjects: ["equação de reação", "espécie química", "coeficiente estequiométrico"], conventions: ["reagentes à esquerda", "produtos à direita", "estados e condições explícitos"], appropriateWhen: ["a transformação química simbólica é parte da tarefa"], avoidWhen: ["a tarefa exige somente descrição macroscópica"], technologies: ["HTML semântico", "notação química estruturada"], practiceModes: ["exposition", "gap", "typing", "selection"] }), responseCompatibility: Object.freeze(["aralearn.response.gap", "aralearn.response.choice"]), limitations: Object.freeze(["Não substitui a explicação microscópica ou energética da reação." ]), accessibility: "A equação possui descrição textual com nomes, coeficientes e estados." }),
  authoringContract: Object.freeze({ intent: "Declare espécies semanticamente, sem desenhar a equação.", required: Object.freeze(["reactionType", "reactants", "products"]), optional: Object.freeze(["prompt", "conditions"]), rules: Object.freeze(["Fórmula e nome são obrigatórios.", "Coeficiente omitido equivale visualmente a um."]), example: Object.freeze({ prompt: "Observe a formação de água.", reactionType: "forward", reactants: [{ id: "h", formula: "H₂", name: "hidrogênio", coefficient: 2, state: "g" }, { id: "o", formula: "O₂", name: "oxigênio", state: "g" }], products: [{ id: "w", formula: "H₂O", name: "água", coefficient: 2, state: "l" }], conditions: [] }) }),
  schema: Object.freeze({ type: "object", additionalProperties: false, required: ["reactionType", "reactants", "products"], properties: { prompt: { type: "string" }, reactionType: { type: "string", enum: ["forward", "reversible", "equilibrium"] }, reactants: { type: "array", minItems: 1, items: { type: "object", additionalProperties: false, required: ["id", "formula", "name"], properties: { id: { type: "string" }, formula: { type: "string" }, name: { type: "string" }, coefficient: { anyOf: [{ type: "integer", minimum: 1 }, { type: "string", minLength: 1 }] }, state: { type: "string", enum: ["s", "l", "g", "aq"] }, charge: { type: "integer" } } } }, products: { type: "array", minItems: 1, items: { type: "object", additionalProperties: false, required: ["id", "formula", "name"], properties: { id: { type: "string" }, formula: { type: "string" }, name: { type: "string" }, coefficient: { anyOf: [{ type: "integer", minimum: 1 }, { type: "string", minLength: 1 }] }, state: { type: "string", enum: ["s", "l", "g", "aq"] }, charge: { type: "integer" } } } }, conditions: { type: "array", items: { type: "string" } } } }),
  normalize(data) { const normalizeSpecies = (items) => (items || []).map((item) => ({ id: String(item?.id || "").trim(), formula: String(item?.formula || "").trim(), name: String(item?.name || "").trim(), ...(item?.coefficient != null ? { coefficient: item.coefficient } : {}), ...(item?.state ? { state: String(item.state) } : {}), ...(Number.isInteger(item?.charge) ? { charge: item.charge } : {}) })); return { ...(data?.prompt ? { prompt: String(data.prompt).trim() } : {}), reactionType: String(data?.reactionType || "forward"), reactants: normalizeSpecies(data?.reactants), products: normalizeSpecies(data?.products), ...(data?.conditions ? { conditions: data.conditions.map(String) } : {}) }; },
  validate(data) { const ids = [...data.reactants, ...data.products].map(({ id }) => id); return new Set(ids).size === ids.length ? [] : ["Espécies precisam de ids únicos."]; },
  render(data) { const arrow = data.reactionType === "forward" ? "→" : data.reactionType === "reversible" ? "⇄" : "⇌"; return `<div class="runtime-block runtime-reaction-block">${data.prompt ? renderPackageProse(data.prompt) : ""}<figure class="package-reaction"><div class="package-reaction-equation" role="img" aria-label="${escapePackageAttribute(reactionAccessibleText(data))}"><span class="package-reaction-side">${renderSide(data.reactants)}</span><span class="package-reaction-arrow" aria-hidden="true">${arrow}</span><span class="package-reaction-side">${renderSide(data.products)}</span></div>${data.conditions?.length ? `<figcaption class="package-reaction-conditions"><strong>Condições</strong>${data.conditions.map((condition) => `<span>${renderPackageInline(condition)}</span>`).join("")}</figcaption>` : ""}</figure></div>`; },
  accessibleText(data) { return reactionAccessibleText(data); },
  editableTargets(data) { return [...data.reactants.map((_, index) => ({ path: `reactants[${index}].name`, label: `Editar reagente ${index + 1}` })), ...data.products.map((_, index) => ({ path: `products[${index}].name`, label: `Editar produto ${index + 1}` }))]; }
});
