-- Presentation metadata only: parameter identities, values and assignments are preserved.
begin;
lock table private.course_design_parameter_definitions in access exclusive mode;
create temporary table parameter_semantics_before_306 on commit drop as
  select parameter_id,ordinal,value_kind,supported_scopes,default_value,
    definition-array['label','group','groupLabel'] as definition
  from private.course_design_parameter_definitions;
do $preflight$ begin
  if (select count(*) from private.course_design_parameter_definitions)<>12
    or exists(select 1 from private.course_design_parameter_definitions where catalog_version<>'1.2.0') then
    raise exception 'Catálogo anterior inesperado.' using errcode='55000'; end if;
end $preflight$;
alter table private.course_design_parameter_definitions disable trigger course_design_parameter_definitions_immutable_v1;
alter table private.course_design_parameter_definitions drop constraint course_design_parameter_definitions_id_v1;
alter table private.course_design_parameter_definitions add constraint course_design_parameter_definitions_id_v2 check(
  parameter_id~'^[a-z][a-z0-9_]{0,159}$' and catalog_version='1.2.1' and ordinal between 1 and 12) not valid;
-- COURSE_DESIGN_CATALOG_BEGIN
-- Gerado por scripts/syncCourseDesignParameterCatalog.mjs; fonte: src/domain/courseDesignParameters.js.
insert into private.course_design_parameter_definitions(parameter_id,ordinal,catalog_version,value_kind,supported_scopes,definition,default_value) values
('new_analysis_unit_ceiling_per_expository_study_unit',1,'1.2.1','integer',array['course','lesson','didactic_microsequence','study_unit']::text[],'{"id":"new_analysis_unit_ceiling_per_expository_study_unit","humanField":"maximo_ideias_novas_por_unidade","group":"content","groupLabel":"Explicações","unitLabel":"identidades introduzidas","optionLabels":{},"label":"Novas unidades de análise","construct":"Quantidade de unidades da análise instrucional introduzidas como novas em uma mesma unidade de estudo expositiva.","operationalization":"Conta identidades distintas declaradas como introduzidas em cada unidade expositiva ou mista; não usa caracteres, linhas, altura nem tempo como proxy.","limitations":"A contagem orienta granularidade de desenho e não mede carga cognitiva, dificuldade, aprendizagem ou qualidade da explicação.","defaultStatus":"product_hypothesis","evidenceRefs":["koedinger2012kli","chen2023elementinteractivity"],"supportedScopes":["course","lesson","didactic_microsequence","study_unit"],"valueSchema":{"type":"integer","minimum":1,"maximum":64},"defaultValue":2}'::jsonb,'2'::jsonb),
('required_explanation_forms',2,'1.2.1','set',array['course','lesson','didactic_microsequence','study_unit']::text[],'{"id":"required_explanation_forms","humanField":"formas_de_explicacao","group":"content","groupLabel":"Explicações","unitLabel":"formas de explicação","optionLabels":{"plain_definition":"Definição","concrete_example":"Exemplo concreto","mechanism":"Mecanismo","contrast":"Contraste","application_condition":"Condição de aplicação","limit_or_exception":"Limite ou exceção","worked_example":"Exemplo resolvido","representation_link":"Relação entre representações"},"label":"Formas de explicação","construct":"Formas semanticamente distintas usadas para desenvolver uma unidade da análise instrucional.","operationalization":"Verifica, por identidade introduzida, quais formas foram desenvolvidas e quais foram declaradas não aplicáveis com motivo factual.","limitations":"As formas não são uma escala de qualidade nem uma lista universal; adequação depende do objeto, público, tarefa e representação.","defaultStatus":"product_hypothesis","evidenceRefs":["wittwer2008explanations","ainsworth2006deft"],"supportedScopes":["course","lesson","didactic_microsequence","study_unit"],"valueSchema":{"type":"set","allowedValues":["plain_definition","concrete_example","mechanism","contrast","application_condition","limit_or_exception","worked_example","representation_link"],"minimumItems":1,"maximumItems":8},"defaultValue":["plain_definition","concrete_example","mechanism","contrast"]}'::jsonb,'["plain_definition","concrete_example","mechanism","contrast"]'::jsonb),
('minimum_distinct_practice_opportunities_per_evidence_requirement',3,'1.2.1','integer',array['course','lesson','didactic_microsequence','study_unit']::text[],'{"id":"minimum_distinct_practice_opportunities_per_evidence_requirement","humanField":"oportunidades_distintas_por_requisito","group":"practice","groupLabel":"Prática","unitLabel":"oportunidades distintas","optionLabels":{},"label":"Oportunidades por requisito","construct":"Quantidade mínima de oportunidades semanticamente distintas relacionadas a cada requisito de evidência.","operationalization":"Conta opportunityId distinto por requisito de evidência e conserva a operação-alvo invariável declarada em cada oportunidade.","limitations":"Quantidade de oportunidades não demonstra domínio, eficácia ou equivalência entre tarefas; a pertinência da evidência permanece uma hipótese de desenho.","defaultStatus":"product_hypothesis","evidenceRefs":["karpicke2008retrieval","mislevy2003ecd"],"supportedScopes":["course","lesson","didactic_microsequence","study_unit"],"valueSchema":{"type":"integer","minimum":1,"maximum":64},"defaultValue":2}'::jsonb,'2'::jsonb),
('required_practice_variation_dimensions',4,'1.2.1','set',array['course','lesson','didactic_microsequence','study_unit']::text[],'{"id":"required_practice_variation_dimensions","humanField":"dimensoes_de_variacao_da_pratica","group":"practice","groupLabel":"Prática","unitLabel":"dimensões de variação","optionLabels":{"case_or_data":"Caso ou dados","context":"Contexto","task_feature":"Característica da tarefa","external_representation":"Representação","support_level":"Nível de apoio"},"label":"Variação da prática","construct":"Dimensões semanticamente relevantes que variam entre oportunidades relacionadas ao mesmo requisito de evidência.","operationalization":"Verifica as dimensões declaradas nas oportunidades sem tratar mudança cosmética ou reordenação como variação semântica.","limitations":"Variação declarada não prova transferência nem aprendizagem e precisa preservar a operação-alvo pertinente ao requisito.","defaultStatus":"product_hypothesis","evidenceRefs":["taylor2010interleaved","ainsworth2006deft"],"supportedScopes":["course","lesson","didactic_microsequence","study_unit"],"valueSchema":{"type":"set","allowedValues":["case_or_data","context","task_feature","external_representation","support_level"],"minimumItems":1,"maximumItems":5},"defaultValue":["case_or_data"]}'::jsonb,'["case_or_data"]'::jsonb),
('authoring_chat_response_word_target',5,'1.2.1','integer',array['course','lesson','didactic_microsequence','study_unit']::text[],'{"id":"authoring_chat_response_word_target","humanField":"alvo_palavras_conversa","group":"conversation","groupLabel":"Conversa","unitLabel":"palavras por resposta","optionLabels":{},"label":"Extensão das respostas","construct":"Extensão editorial pretendida para uma resposta do assistente durante a autoria.","operationalization":"Informa ao assistente um alvo flexível de palavras para a decisão corrente; respostas podem ultrapassá-lo quando a inspeção ou a segurança exigir.","limitations":"O alvo não é limite rígido e não autoriza esconder decisões educacionais, reduzir cobertura nem expor detalhes internos.","defaultStatus":"product_hypothesis","evidenceRefs":[],"supportedScopes":["course","lesson","didactic_microsequence","study_unit"],"valueSchema":{"type":"integer","minimum":20,"maximum":500},"defaultValue":120}'::jsonb,'120'::jsonb),
('study_unit_content_word_target',6,'1.2.1','integer',array['course','lesson','didactic_microsequence','study_unit']::text[],'{"id":"study_unit_content_word_target","humanField":"alvo_palavras_unidade","group":"editorial","groupLabel":"Leitura e estilo","unitLabel":"palavras por unidade","optionLabels":{},"label":"Extensão das unidades","construct":"Extensão editorial pretendida para o conteúdo de uma unidade de estudo focal.","operationalization":"Orienta a distribuição do conteúdo em torno de um alvo flexível, depois de satisfeitas a função didática e as dependências necessárias.","limitations":"O alvo não é máximo, não mede qualidade ou carga cognitiva e não justifica compactação nem atomização.","defaultStatus":"product_hypothesis","evidenceRefs":[],"supportedScopes":["course","lesson","didactic_microsequence","study_unit"],"valueSchema":{"type":"integer","minimum":40,"maximum":1000},"defaultValue":180}'::jsonb,'180'::jsonb),
('practice_distribution',7,'1.2.1','enum',array['course','lesson','didactic_microsequence','study_unit']::text[],'{"id":"practice_distribution","humanField":"distribuicao_da_pratica","group":"practice","groupLabel":"Prática","unitLabel":"organização da sequência","label":"Distribuição das práticas","construct":"Organização das oportunidades de prática entre as exposições.","operationalization":"Observa posições e intervalos das unidades declaradas expositivas, práticas ou mistas; intercalar prefere prática entre exposições e agrupar prefere blocos.","limitations":"A distribuição é contextual; uma sequência curta ou mista não permite certificar alternância nem qualidade por contagem.","defaultStatus":"product_hypothesis","evidenceRefs":[],"supportedScopes":["course","lesson","didactic_microsequence","study_unit"],"valueSchema":{"type":"enum","allowedValues":["interleaved","clustered"]},"optionLabels":{"interleaved":"Intercalada","clustered":"Agrupada"},"defaultValue":"interleaved"}'::jsonb,'"interleaved"'::jsonb),
('practice_position',8,'1.2.1','enum',array['course','lesson','didactic_microsequence','study_unit']::text[],'{"id":"practice_position","humanField":"posicao_da_pratica","group":"practice","groupLabel":"Prática","unitLabel":"posição em relação à explicação","label":"Posição das práticas","construct":"Posição pretendida da prática em relação à explicação pertinente.","operationalization":"Orienta prática antes, depois ou antes e depois da explicação; posições declaradas são observáveis sem inferir equivalência semântica.","limitations":"A posição não demonstra recuperação, domínio ou eficácia e precisa de justificativa compatível com o repertório e o objetivo.","defaultStatus":"product_hypothesis","evidenceRefs":[],"supportedScopes":["course","lesson","didactic_microsequence","study_unit"],"valueSchema":{"type":"enum","allowedValues":["before_explanation","after_explanation","before_and_after"]},"optionLabels":{"before_explanation":"Antes da explicação","after_explanation":"Depois da explicação","before_and_after":"Antes e depois"},"defaultValue":"after_explanation"}'::jsonb,'"after_explanation"'::jsonb),
('authoring_part_microsequence_target',9,'1.2.1','integer',array['course']::text[],'{"id":"authoring_part_microsequence_target","humanField":"alvo_microssequencias_por_parte","group":"cadence","groupLabel":"Produção","unitLabel":"microssequências por parte","label":"Granularidade da parte","construct":"Tamanho contextual da parte de produção, independente da quantidade de conteúdo curricular.","operationalization":"Orienta quantas microssequências existentes uma parte de produção pretende reunir, preservando cobertura, dependências e limites de transporte.","limitations":"Uma parte é uma organização de trabalho; não é unidade curricular nem autoriza truncar material ou dividir identidades para caber.","defaultStatus":"product_hypothesis","evidenceRefs":[],"supportedScopes":["course"],"valueSchema":{"type":"integer","minimum":1,"maximum":64},"optionLabels":{},"defaultValue":1}'::jsonb,'1'::jsonb),
('authoring_batch_part_target',10,'1.2.1','integer',array['course']::text[],'{"id":"authoring_batch_part_target","humanField":"alvo_partes_por_lote","group":"cadence","groupLabel":"Produção","unitLabel":"partes por lote","label":"Granularidade do lote","construct":"Quantidade contextual de partes a preparar no mesmo lote autorizado.","operationalization":"Orienta a cadência do trabalho mantendo cada parte e sua confirmação; não altera automaticamente frequência de pausa.","limitations":"Número de lotes não mede conteúdo nem aprendizagem e não amplia o mandato de aplicar propostas.","defaultStatus":"product_hypothesis","evidenceRefs":[],"supportedScopes":["course"],"valueSchema":{"type":"integer","minimum":1,"maximum":64},"optionLabels":{},"defaultValue":1}'::jsonb,'1'::jsonb),
('authoring_pause_frequency',11,'1.2.1','enum',array['course']::text[],'{"id":"authoring_pause_frequency","humanField":"frequencia_de_pausa","group":"cadence","groupLabel":"Produção","unitLabel":"momento de pausa","label":"Frequência de pausa","construct":"Preferência por pontos de discussão e revisão durante a produção.","operationalization":"Define pontos de pausa por microssequência, parte, lote ou solicitação; permanece independente da granularidade da parte e do lote.","limitations":"A preferência não remove confirmações de aplicação, autorização do autor nem limites operacionais.","defaultStatus":"product_hypothesis","evidenceRefs":[],"supportedScopes":["course"],"valueSchema":{"type":"enum","allowedValues":["each_microsequence","each_part","each_batch","on_request"]},"optionLabels":{"each_microsequence":"A cada microssequência","each_part":"A cada parte","each_batch":"A cada lote","on_request":"Quando solicitado"},"defaultValue":"each_part"}'::jsonb,'"each_part"'::jsonb),
('authoring_chat_interaction',12,'1.2.1','enum',array['course','lesson','didactic_microsequence','study_unit']::text[],'{"id":"authoring_chat_interaction","humanField":"preferencia_da_conversa","group":"conversation","groupLabel":"Conversa","unitLabel":"forma da conversa","label":"Preferência da conversa","construct":"Preferência editorial por concisão, debate ou explicação na conversa de autoria.","operationalization":"Orienta como o assistente discute a decisão corrente: concisão, exame de alternativas e argumentos, ou explicação desenvolvida.","limitations":"Concisão no chat não autoriza resumir material didático, ocultar incerteza ou substituir a decisão humana.","defaultStatus":"product_hypothesis","evidenceRefs":[],"supportedScopes":["course","lesson","didactic_microsequence","study_unit"],"valueSchema":{"type":"enum","allowedValues":["concise","debate","explanation"]},"optionLabels":{"concise":"Concisão","debate":"Debate","explanation":"Explicação"},"defaultValue":"concise"}'::jsonb,'"concise"'::jsonb)
on conflict(parameter_id) do update set ordinal=excluded.ordinal,catalog_version=excluded.catalog_version,value_kind=excluded.value_kind,supported_scopes=excluded.supported_scopes,definition=excluded.definition,default_value=excluded.default_value;
-- COURSE_DESIGN_CATALOG_END
alter table private.course_design_parameter_definitions validate constraint course_design_parameter_definitions_id_v2;
alter table private.course_design_parameter_definitions enable trigger course_design_parameter_definitions_immutable_v1;
do $metadata_only$ begin
  if exists(select * from parameter_semantics_before_306 except select parameter_id,ordinal,value_kind,supported_scopes,default_value,
      definition-array['label','group','groupLabel'] from private.course_design_parameter_definitions)
    or exists(select parameter_id,ordinal,value_kind,supported_scopes,default_value,definition-array['label','group','groupLabel']
      from private.course_design_parameter_definitions except select * from parameter_semantics_before_306) then
    raise exception 'A apresentação alteraria a semântica de um parâmetro.' using errcode='23514'; end if;
end $metadata_only$;
do $catalog_read_and_snapshot$ declare v text; begin
  select pg_get_functiondef('public.get_owned_course_design_for_actor_v3(uuid,uuid,text,text,integer,text)'::regprocedure) into v;
  if position('''parameterCatalogVersion'',''1.2.0''' in v)=0 then raise exception 'Leitor de desenho inesperado.'; end if;
  execute replace(v,'''parameterCatalogVersion'',''1.2.0''','''parameterCatalogVersion'',''1.2.1''');
  select pg_get_functiondef('private.materialize_course_authoring_part_core_v1(uuid,uuid,uuid,bigint,bigint,jsonb,text,text)'::regprocedure) into v;
  if position('v_snapshot->>''parameterCatalogVersion''<>''1.2.0''' in v)=0 then raise exception 'Writer de aplicação inesperado.'; end if;
  -- These versions have identical identities/value domains/meaning. Historical
  -- snapshots remain literal; all existing checks of values, origin and scope stay.
  execute replace(v,'v_snapshot->>''parameterCatalogVersion''<>''1.2.0''',
    'v_snapshot->>''parameterCatalogVersion'' not in (''1.2.0'',''1.2.1'')');
end $catalog_read_and_snapshot$;
do $manifest$ declare v jsonb; begin
 v:=public.get_aralearn_runtime_manifest()||jsonb_build_object('schemaRevision','20260905162000');
 v:=jsonb_set(v,'{features}',(v->'features')||'["course-authoring-export-v1"]'::jsonb);
 execute format('create or replace function public.get_aralearn_runtime_manifest() returns jsonb language sql stable security definer set search_path=pg_catalog as %L','select '||quote_literal(v::text)||'::jsonb');
end $manifest$;
commit;
